// GENERATED by tools/9s1z/extract-deps.sh — DO NOT EDIT.
// Verbatim line-range extracts from the app target. playhead-9s1z, measurement only.
import Foundation

// --- FoundationModelClassifier.swift 206-300 (inside the #else, non-FoundationModels branch)
enum TranscriptQuality: String, Sendable, Codable, Hashable {
    case good
    case degraded
    case unusable
}

enum CoarseDisposition: String, Sendable, Codable, Hashable {
    case noAds
    case containsAd
    case uncertain
    case abstain
}

enum CertaintyBand: String, Sendable, Codable, Hashable {
    case weak
    case moderate
    case strong
}

struct CoarseSupportSchema: Sendable, Codable, Hashable {
    var supportLineRefs: [Int]
    var certainty: CertaintyBand
}

struct CoarseScreeningSchema: Sendable, Codable, Hashable {
    var disposition: CoarseDisposition
    var support: CoarseSupportSchema?
}

enum CommercialIntent: String, Sendable, Codable, Hashable, CaseIterable {
    case paid
    case owned
    case affiliate
    case organic
    case unknown
}

enum Ownership: String, Sendable, Codable, Hashable {
    case thirdParty
    case show
    case network
    case guest
    case unknown
}

enum BoundaryPrecision: String, Sendable, Codable, Hashable {
    // Cycle 2 H5: `.rough` removed (see iOS 26+ branch for rationale).
    case usable
    case precise
}

enum AlternativeExplanation: String, Sendable, Codable, Hashable {
    case none
    case editorialContext
    case guestPromotion
    case showCredits
    case unknown
}

enum ReasonTag: String, Sendable, Codable, Hashable {
    case callToAction
    case urlMention
    case promoCode
    case disclosure
    case brandMention
    case crossPromoLanguage
    case hostReadPitch
    case guestPlug
}

enum EvidenceAnchorKind: String, Sendable, Codable, Hashable {
    case url
    case promoCode
    case ctaPhrase
    case disclosurePhrase
    case brandSpan
}

struct EvidenceAnchorSchema: Sendable, Codable, Hashable {
    var evidenceRef: Int?
    var lineRef: Int
    var kind: EvidenceAnchorKind
    var certainty: CertaintyBand
}

struct SpanRefinementSchema: Sendable, Codable, Hashable {
    var commercialIntent: CommercialIntent
    var ownership: Ownership
    var firstLineRef: Int
    var lastLineRef: Int
    var certainty: CertaintyBand
    var boundaryPrecision: BoundaryPrecision
    var evidenceAnchors: [EvidenceAnchorSchema]
}


// --- TranscriptSegmenter.swift 1-66 (AdTranscriptSegment + its two enums)
import Foundation

// MARK: - AdTranscriptSegment

/// A coherent region of transcript atoms grouped by natural boundaries.
/// Named `AdTranscriptSegment` to avoid collision with the ASR-layer `TranscriptSegment`.
struct AdTranscriptSegment: Sendable {
    /// The atoms in this segment, ordered by ordinal.
    let atoms: [TranscriptAtom]
    /// Index of this segment within the episode.
    let segmentIndex: Int
    /// Why this segment started where it did.
    let boundaryReason: AdTranscriptBoundaryReason
    /// Confidence in the boundary that started this segment, 0.0...1.0.
    let boundaryConfidence: Double
    /// Semantic type of the segment. Phase 1 segments are speech-only.
    let segmentType: AdTranscriptSegmentType

    init(
        atoms: [TranscriptAtom],
        segmentIndex: Int,
        boundaryReason: AdTranscriptBoundaryReason = .startOfTranscript,
        boundaryConfidence: Double = 1.0,
        segmentType: AdTranscriptSegmentType = .speech
    ) {
        self.atoms = atoms
        self.segmentIndex = segmentIndex
        self.boundaryReason = boundaryReason
        self.boundaryConfidence = boundaryConfidence
        self.segmentType = segmentType
    }

    /// playhead-r5um / playhead-csbq: min/max, not first/last. Since r5um the
    /// atom sequence is time-ordered, so for the ordinary non-overlapping ASR
    /// case these are byte-identical to `first`/`last`. They differ — and
    /// first/last would UNDERSTATE the span — when one atom's interval nests
    /// inside another's, which the canonicalizer reaches by design: it RETAINS
    /// a fast chunk that only partially overlaps a final interval
    /// (`residualFastFinalOverlapCount`), so a long final atom can be followed
    /// by a short fast one. csbq had to repair three window-bound producers
    /// that projected a span with first/last; these are the same projection
    /// one level down, and a segment whose end precedes its start is exactly
    /// the geometry `AnalysisStore.insertSemanticScanResult` now rejects.
    var startTime: Double { atoms.map(\.startTime).min() ?? 0 }
    var endTime: Double { atoms.map(\.endTime).max() ?? 0 }
    var duration: Double { endTime - startTime }
    /// Ordinals, unlike times, are array positions assigned by `atomize`, so
    /// first/last is correct by construction here.
    var firstAtomOrdinal: Int { atoms.first?.atomKey.atomOrdinal ?? 0 }
    var lastAtomOrdinal: Int { atoms.last?.atomKey.atomOrdinal ?? 0 }
    var text: String { atoms.map(\.text).joined(separator: " ") }
}

enum AdTranscriptBoundaryReason: String, Sendable, Codable {
    case startOfTranscript
    case maxDuration
    case pause
    case speakerTurn
    case discourseMarker
    case sentenceBoundary
}

enum AdTranscriptSegmentType: String, Sendable, Codable {
    case speech
}


// --- TranscriptEngine.swift 19-167 (TranscriptWord, WeakAnchorPhrase, TranscriptWeakAnchorMetadata)
/// A single word with precise timing from the ASR pass.
struct TranscriptWord: Sendable, Equatable {
    let text: String
    /// Start time in seconds relative to the episode audio.
    let startTime: TimeInterval
    /// End time in seconds relative to the episode audio.
    let endTime: TimeInterval
    /// Model confidence, 0.0...1.0.
    let confidence: Float
}

struct WeakAnchorPhrase: Sendable, Codable, Equatable {
    let text: String
    let startTime: TimeInterval
    let endTime: TimeInterval
    let confidence: Double

    func offsettingTimes(by delta: TimeInterval) -> WeakAnchorPhrase {
        WeakAnchorPhrase(
            text: text,
            startTime: startTime + delta,
            endTime: endTime + delta,
            confidence: confidence
        )
    }
}

struct TranscriptWeakAnchorMetadata: Sendable, Codable, Equatable {
    typealias LowConfidencePhrase = WeakAnchorPhrase

    private struct PhraseSignature: Hashable {
        let text: String
        let startMicroseconds: Int
        let endMicroseconds: Int

        init(_ phrase: WeakAnchorPhrase) {
            self.text = phrase.text.trimmingCharacters(in: .whitespacesAndNewlines).lowercased()
            self.startMicroseconds = Int((phrase.startTime * 1_000_000).rounded())
            self.endMicroseconds = Int((phrase.endTime * 1_000_000).rounded())
        }
    }

    let averageConfidence: Double
    let minimumConfidence: Double
    let alternativeTexts: [String]
    let lowConfidencePhrases: [WeakAnchorPhrase]

    var hasRecoveryText: Bool {
        !alternativeTexts.isEmpty || !lowConfidencePhrases.isEmpty
    }

    func offsettingTimes(by delta: TimeInterval) -> TranscriptWeakAnchorMetadata {
        TranscriptWeakAnchorMetadata(
            averageConfidence: averageConfidence,
            minimumConfidence: minimumConfidence,
            alternativeTexts: alternativeTexts,
            lowConfidencePhrases: lowConfidencePhrases.map { $0.offsettingTimes(by: delta) }
        )
    }

    func merged(with other: TranscriptWeakAnchorMetadata) -> TranscriptWeakAnchorMetadata {
        var seenAlternatives = Set<String>()
        let mergedAlternatives = (alternativeTexts + other.alternativeTexts).filter { text in
            let normalized = text.trimmingCharacters(in: .whitespacesAndNewlines).lowercased()
            guard !normalized.isEmpty else { return false }
            return seenAlternatives.insert(normalized).inserted
        }

        var seenPhrases = Set<PhraseSignature>()
        let mergedPhrases = (lowConfidencePhrases + other.lowConfidencePhrases).filter { phrase in
            seenPhrases.insert(PhraseSignature(phrase)).inserted
        }

        return TranscriptWeakAnchorMetadata(
            averageConfidence: min(averageConfidence, other.averageConfidence),
            minimumConfidence: min(minimumConfidence, other.minimumConfidence),
            alternativeTexts: mergedAlternatives,
            lowConfidencePhrases: mergedPhrases
        )
    }

    static func build(
        primaryText: String,
        words: [TranscriptWord],
        alternatives: [String],
        startTime: TimeInterval,
        endTime: TimeInterval,
        lowConfidenceThreshold: Float = 0.6
    ) -> TranscriptWeakAnchorMetadata? {
        guard !words.isEmpty || !alternatives.isEmpty || !primaryText.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else {
            return nil
        }

        let averageConfidence: Double
        let minimumConfidence: Double
        if words.isEmpty {
            averageConfidence = 1.0
            minimumConfidence = 1.0
        } else {
            let confidences = words.map { Double($0.confidence) }
            averageConfidence = confidences.reduce(0, +) / Double(confidences.count)
            minimumConfidence = confidences.min() ?? 1.0
        }

        var phrases: [WeakAnchorPhrase] = []
        var currentGroup: [TranscriptWord] = []

        func flushGroup() {
            guard let first = currentGroup.first, let last = currentGroup.last else { return }
            phrases.append(
                WeakAnchorPhrase(
                    text: currentGroup.map(\.text).joined(separator: " "),
                    startTime: first.startTime,
                    endTime: max(first.endTime, last.endTime),
                    confidence: currentGroup.map { Double($0.confidence) }.min() ?? 1.0
                )
            )
            currentGroup.removeAll(keepingCapacity: true)
        }

        for word in words {
            if word.confidence < lowConfidenceThreshold {
                currentGroup.append(word)
            } else {
                flushGroup()
            }
        }
        flushGroup()

        return TranscriptWeakAnchorMetadata(
            averageConfidence: averageConfidence,
            minimumConfidence: minimumConfidence,
            alternativeTexts: alternatives.filter {
                !$0.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty
                    && $0.caseInsensitiveCompare(primaryText) != .orderedSame
            },
            lowConfidencePhrases: phrases.isEmpty && !words.isEmpty && minimumConfidence < Double(lowConfidenceThreshold)
                ? [
                    WeakAnchorPhrase(
                        text: primaryText,
                        startTime: startTime,
                        endTime: endTime,
                        confidence: minimumConfidence
                    )
                ]
                : phrases
        )
    }
}

// --- TranscriptEngine.swift 217-221 (TranscriptPassType)
/// Distinguishes fast-path (real-time) from final-path (backfill) results.
enum TranscriptPassType: String, Sendable, Codable {
    case fast
    case final_ = "final"
}

// --- SpanExtentSupport.swift 1-134 + 175 (the SpanExtentSupport struct;
// --- 136-174 is derive(anchorProvenance:stingerTrace:), which reaches AnchorRef
// --- and StingerRefinementTrace. The composer uses only `.unanchored`.)
// SpanExtentSupport.swift
// playhead-2350: EXTENT (boundary) support, represented separately from PRESENCE.
//
// Why this exists
// ---------------
// Fusion produced ONE number — `DecisionResult.skipConfidence` — and used it for
// two different jobs: "is there an ad here?" (PRESENCE) and "does this span cover
// the ad?" (EXTENT). The 2026-07-25 THEMOVE Catalyst replay is what that costs: FM
// coarse scans correctly reported `containsAd` over huge windows (17.04–1183.62,
// 49.02–1376.94, 3010.44–3575.88) while fusion attached that presence mass to
// narrow lexical/music SEEDS and shipped the seed geometry as the ad. Every
// persisted edge was `.unanchored`, yet every window carried
// `eligibilityGate == .eligible` and the correct-show arm made all four
// `autoSkipEligible`. One of those seeds began 12.72 s inside the host's sign-off.
//
// A span with strong presence evidence and invented edges is a BANNER, never a
// skip. This type is the extent half of the verdict: it says how well each edge
// is INDEPENDENTLY supported, and it is the sole input to the unanchored-edge
// auto-skip block applied in
// `DecisionResult.withExtentSupport(_:blockingUnanchoredAutoSkip:)`.
//
// Deliberately NOT in scope (playhead-4xqf owns it): inferring wider boundaries.
// This type never moves an edge. It only reports how much the existing edges are
// worth.
//
// SCOPE OF THE INVARIANT — read this before assuming it is global. The block
// declared in this file is applied in `AdDetectionService.runBackfill`'s
// emission loop, so it covers the FUSED verdict only.
//
// The hot path (`runHotPath` / the segment-aggregator promotion) is a SECOND
// producer that reaches auto-skip. It stamps `AdWindow.eligibilityGate` from
// `precisionGateLabel`, whose `"autoSkip"` literal is not a
// `SkipEligibilityGate` raw value and therefore rides the orchestrator's legacy
// nil-gate contract straight into the auto-skip path — and neither hot-path
// site sets the edge-anchor columns, so those rows are `.unanchored` by
// construction. 2350 left that hole open and tracked it as an adjacent finding.
//
// playhead-bllt CLOSED IT, in `HotPathExtentGate` — a separate file because it
// is a separate producer with a different verdict type (a persisted label
// string, not a `DecisionResult`), reading the SAME `SpanExtentSupport` and
// keyed on the SAME `AdDetectionConfig.unanchoredExtentBlocksAutoSkip` flag so
// one kill switch governs both producers and cannot half-fire. Read that file's
// header for the hot path's side of the rule.

import Foundation

// MARK: - ExtentAnchorTier

/// How well ONE edge of a span is independently supported, as an ORDINAL tier.
///
/// Deliberately a tier, not a probability: the pipeline has no calibrated
/// per-edge boundary likelihood, and manufacturing one would repeat the exact
/// mistake this bead fixes. The measured per-tier edge error that motivates the
/// ordering lives in `docs/autoskip-edge-padding-derivation-2026-07-20.md`
/// (`AutoSkipEdgePadding`'s margins are derived from the same evidence).
///
/// Conformances are deliberately minimal — no `CaseIterable`, no `Codable`. The
/// tier is derived from `AutoSkipEdgeAnchor` on demand and is not persisted (the
/// per-edge anchor raw values already are, on the `ad_windows` row), so a
/// speculative conformance would only be a shape to maintain. Add one when a
/// caller actually needs it. Mirrors the playhead-fqc8 `PromotionTrack` call.
enum ExtentAnchorTier: Int, Sendable, Hashable, Comparable {
    /// No independent support: the edge is where an FM/lexical/aggregator seed
    /// happened to land. The pipeline invented it.
    case none = 0
    /// Corroborated by an independent acoustic observation of the same edge —
    /// today, a `StingerRefiner` snap onto a per-show stinger bank match.
    case corroborated = 1
    /// Deterministic: the byte-exact rediff differ proved the origin served
    /// different bytes at this edge.
    case deterministic = 2

    static func < (lhs: Self, rhs: Self) -> Bool { lhs.rawValue < rhs.rawValue }
}

extension AutoSkipEdgeAnchor {
    /// The extent tier this anchor provenance is worth. One definition, shared
    /// by the gate and by diagnostics, so "anchored" cannot drift between them.
    var extentTier: ExtentAnchorTier {
        switch self {
        case .rediffByteExact: return .deterministic
        case .stingerSnapped: return .corroborated
        case .unanchored: return .none
        }
    }
}

// MARK: - SpanExtentSupport

/// The EXTENT half of a fused verdict: per-edge anchor provenance and the tier
/// it is worth. Pure value type; carries no scores and no geometry.
///
/// Start and end are tracked INDEPENDENTLY — a span with a byte-exact start and
/// an invented end is not "half safe", it is unsafe, because the invented edge
/// is the one that clips content.
struct SpanExtentSupport: Sendable, Equatable, Hashable {
    /// Provenance tier of the leading edge.
    let startAnchor: AutoSkipEdgeAnchor
    /// Provenance tier of the trailing edge.
    let endAnchor: AutoSkipEdgeAnchor

    /// The conservative default: neither edge is independently supported. This
    /// is what a span gets when nothing proved its geometry — including any
    /// call site that has not yet derived extent support.
    static let unanchored = SpanExtentSupport(
        startAnchor: .unanchored,
        endAnchor: .unanchored
    )

    var startTier: ExtentAnchorTier { startAnchor.extentTier }
    var endTier: ExtentAnchorTier { endAnchor.extentTier }

    /// A span is only as well-bounded as its WEAKER edge.
    var tier: ExtentAnchorTier { min(startTier, endTier) }

    /// `true` iff BOTH edges are independently supported. This — and only this —
    /// admits a span to auto-skip under playhead-2350.
    var isFullyAnchored: Bool { tier != .none }

    /// Which edges are unanchored, for diagnostics/logging. Stable order.
    var unanchoredEdges: [String] {
        var edges: [String] = []
        if startTier == .none { edges.append("start") }
        if endTier == .none { edges.append("end") }
        return edges
    }

    // No scalar `extentConfidence` is exposed, deliberately. Extent confidence
    // is `tier` — an ordinal — because the pipeline has no calibrated per-edge
    // boundary likelihood to report. A 0.0/0.5/1.0 stand-in would read like a
    // probability, and the first thing anyone does with a probability is compare
    // it to a threshold, which is precisely the presence-shaped reasoning this
    // bead removed from the extent half of the verdict. Add one when there is a
    // real measurement behind it.
}

// --- EvidenceCatalogBuilder.swift 17-23 (EvidenceCategory)
enum EvidenceCategory: String, Sendable, CaseIterable, Codable {
    case url              // URLs, vanity URLs, "dot com slash" patterns
    case promoCode        // Discount/coupon/promo codes
    case ctaPhrase        // Calls to action
    case disclosurePhrase // Sponsorship disclosures
    case brandSpan        // Brand-like proper noun spans in commercial context
}

// --- AutoSkipEdgePadding.swift 135-146 (AutoSkipEdgeAnchor)
enum AutoSkipEdgeAnchor: String, Sendable, Equatable, CaseIterable {
    /// The edge was set by the byte-exact rediff differ (A/B fetch
    /// alignment, playhead-xsdz.44/xsdz.57): byte-verified splice mapped to
    /// the A timeline.
    case rediffByteExact
    /// The edge was snapped by the per-show stinger bank
    /// (`StingerRefiner`, trace `startSnapped` / `endSnapped` true).
    case stingerSnapped
    /// No hard anchor: FM/lexical/aggregator boundary, unsnapped stinger
    /// consult, or unknown provenance. The conservative default.
    case unanchored
}

// --- EvidenceLedgerEntry.swift 17-101 (SkipEligibilityGate)
enum SkipEligibilityGate: String, Sendable, Codable, Equatable, CaseIterable {
    /// Decision is actionable; all quorum and policy requirements are met.
    case eligible
    /// FM-only or weak corroboration: evidence quorum not satisfied.
    case blockedByEvidenceQuorum
    /// External policy (e.g. content type, show-level overrides) prevents skip.
    case blockedByPolicy
    /// Span crosses a high-quality content chapter; eligible for banner only, not auto-skip.
    case markOnly
    /// User previously vetoed this span or region.
    case blockedByUserCorrection
    /// An FM `noAds` consensus covered this span and nothing strong survived it:
    /// the model was asked whether there is an ad here, said no twice at
    /// `.moderate`+ certainty, and no URL/promo-code/sponsor anchor, catalog
    /// entry, fingerprint match, rediff confirmation or FM `containsAd` entry
    /// contradicted it (see ``FMSuppressionGuard`` / ``FMSuppressionApplicator``).
    /// **Blocked — no auto-skip and no banner.**
    ///
    /// playhead-avbn: this case was `cappedByFMSuppression`, documented "capped
    /// to mark-only" and carrying `severity == 1` alongside ``markOnly`` — while
    /// ``SkipOrchestrator`` routed only ``markOnly`` to the suggest tier and
    /// DROPPED this one at playhead-bq70's blocked-gate guard. The name and the
    /// severity promised a banner the surface never emitted.
    ///
    /// Resolved in the direction of the behaviour rather than the name. The
    /// population is by construction the weakest span the pipeline can produce
    /// — the guard already declines to fire when a strong anchor, catalog entry
    /// or fingerprint is present, and the cap additionally requires that no
    /// strong proposal survived — so it is a span the model actively voted down
    /// with nothing corroborating it, and a banner over it is a banner for
    /// something we have positive reason to think is not an ad. The reach that
    /// the old name appeared to promise is recovered upstream instead, by
    /// playhead-avbn's other half: with pass-B refinements and no-work sentinels
    /// no longer manufacturing the `noAds` consensus, spans that never deserved
    /// the cap keep their honest ``eligible`` / ``markOnly`` gate and reach the
    /// user through their own tier.
    ///
    /// Named `blockedBy*` to match every other severity-≥2 case: the point of
    /// the rename is that the name must predict the behaviour.
    case blockedByFMConsensus

    /// playhead-avbn: the raw value ``blockedByFMConsensus`` was persisted under
    /// before the rename. `ad_windows.eligibilityGate` rows written by earlier
    /// builds still carry it, and ``SkipOrchestrator`` fails a gate it cannot
    /// decode CLOSED (`droppedMalformedEligibilityGate`) — so without the alias
    /// the terminal outcome would be unchanged but the census would attribute
    /// every legacy row to a decode fault instead of to the FM consensus that
    /// actually blocked it. The audit trail is the product here; keep it exact.
    static let legacyFMConsensusRawValue = "cappedByFMSuppression"

    /// Accepts the canonical raw value of every case, plus
    /// ``legacyFMConsensusRawValue``. Derived from ``allCases`` rather than a
    /// hand-written switch so a future case cannot be added without also being
    /// decodable. Also backs the synthesized `Codable` conformance, which
    /// routes `init(from:)` through this initializer.
    init?(rawValue: String) {
        if let canonical = Self.allCases.first(where: { $0.rawValue == rawValue }) {
            self = canonical
            return
        }
        if rawValue == Self.legacyFMConsensusRawValue {
            self = .blockedByFMConsensus
            return
        }
        return nil
    }

    /// Restriction severity for ordering: higher means more restrictive.
    /// Used by SpanFinalizer.capEligibility to allow demotions but prevent promotions.
    /// Gates at the same severity level cannot override each other (first writer wins).
    var severity: Int {
        switch self {
        case .eligible: return 0
        case .markOnly: return 1
        case .blockedByEvidenceQuorum: return 2
        case .blockedByPolicy: return 2
        case .blockedByUserCorrection: return 3
        // playhead-avbn: 2, with the other blocked cases — it was 1, which said
        // "no more restrictive than markOnly" and therefore could not demote a
        // markOnly span. A real FM veto outranks a chapter-overlap or self-promo
        // mark, and a gate that blocks must sort with the gates that block.
        case .blockedByFMConsensus: return 2
        }
    }
}

// --- AdDetectionService.swift 1427-1438 (AdDecisionState)
enum AdDecisionState: String, Sendable {
    /// Initial detection from hot path -- skip-ready but not yet confirmed.
    case candidate
    /// Confirmed by backfill re-classification with full context.
    case confirmed
    /// Suppressed: below threshold after backfill re-classification.
    case suppressed
    /// Skip was applied to the listener (audio was skipped).
    case applied
    /// User tapped "Listen" — skip reverted, plays through the ad.
    case reverted
}

// --- AnalysisStore.swift 332-387 (TranscriptChunk)
struct TranscriptChunk: Sendable {
    let id: String
    let analysisAssetId: String
    let segmentFingerprint: String
    let chunkIndex: Int
    let startTime: Double
    let endTime: Double
    let text: String
    let normalizedText: String
    let pass: String // fast | final
    let modelVersion: String
    let transcriptVersion: String?   // nil for fast-pass chunks (version computed on final)
    let atomOrdinal: Int?            // nil for fast-pass chunks
    let weakAnchorMetadata: TranscriptWeakAnchorMetadata?
    let speakerId: Int?              // B7: validated speaker label, nil when unavailable
    let avgConfidence: Float?        // ASR average confidence, nil on legacy/unavailable rows

    init(
        id: String,
        analysisAssetId: String,
        segmentFingerprint: String,
        chunkIndex: Int,
        startTime: Double,
        endTime: Double,
        text: String,
        normalizedText: String,
        pass: String,
        modelVersion: String,
        transcriptVersion: String?,
        atomOrdinal: Int?,
        weakAnchorMetadata: TranscriptWeakAnchorMetadata? = nil,
        speakerId: Int? = nil,
        avgConfidence: Float? = nil
    ) {
        self.id = id
        self.analysisAssetId = analysisAssetId
        self.segmentFingerprint = segmentFingerprint
        self.chunkIndex = chunkIndex
        self.startTime = startTime
        self.endTime = endTime
        self.text = text
        self.normalizedText = normalizedText
        self.pass = pass
        self.modelVersion = modelVersion
        self.transcriptVersion = transcriptVersion
        self.atomOrdinal = atomOrdinal
        self.weakAnchorMetadata = weakAnchorMetadata
        self.speakerId = speakerId
        self.avgConfidence = Self.sanitizedAvgConfidence(avgConfidence)
    }

    static func sanitizedAvgConfidence(_ value: Float?) -> Float? {
        guard let value, value.isFinite else { return nil }
        return min(max(value, 0), 1)
    }
}

// --- AnalysisStore.swift 389-508 + 542-609 (AdWindow; 509-541 is
// --- hasCompatibleCatalogMatchProvenance, skipped: it reaches five catalog
// --- types the composer never touches. Nothing else is omitted.)
struct AdWindow: Sendable {
    let id: String
    let analysisAssetId: String
    let startTime: Double
    let endTime: Double
    /// playhead-ar60: the DETECTION confidence — "how strongly does the
    /// evidence say this span is an ad". Every producer writes this quantity:
    /// the hot-path classifier writes `adProbability`, the segment aggregator
    /// its `segmentScore`, the mark composers their capped mark confidence,
    /// byte-exact rediff and user marks write `1.0`, and (since ar60) the
    /// fusion path writes `DecisionResult.proposalConfidence`.
    ///
    /// It is NOT the number an actuator may gate on. Until ar60 the fusion
    /// path wrote `DecisionResult.skipConfidence` — the post-correction
    /// ACTUATION number — into this same column, so the two quantities shared
    /// one field and every reader saw whichever the producer happened to mean:
    /// on the 2026-08-02 device pull that was 40 of 104 rows, and 5 of them
    /// were admitted to the cross-launch preload only because an unrelated
    /// user correction on the same asset had inflated the value past the 0.7
    /// DETECTOR floor. Actuation now lives in `skipConfidence`; read it
    /// through ``actuationConfidence`` so a producer that records no separate
    /// actuation number still resolves to something.
    let confidence: Double
    /// playhead-ar60: the ACTUATION confidence — "how much permission does the
    /// system have to act on this span", i.e. detection after calibration and
    /// after the user-correction factor. Written by the fusion path only.
    ///
    /// `nil` means the producer has exactly one number and it is in
    /// `confidence`: the hot path, the mark composers, rediff mints, user
    /// marks, and every row written before the V47 split. Do not read this
    /// field directly for a gate — use ``actuationConfidence``.
    let skipConfidence: Double?
    let boundaryState: String
    let decisionState: String
    let detectorVersion: String
    let advertiser: String?
    let product: String?
    let adDescription: String?
    let evidenceText: String?
    let evidenceStartTime: Double?
    let metadataSource: String
    let metadataConfidence: Double?
    let metadataPromptVersion: String?
    let wasSkipped: Bool
    let userDismissedBanner: Bool
    let evidenceSources: String?
    let eligibilityGate: String?
    /// playhead-epfk: top `AdCatalogStore.matches(...)` similarity in
    /// `[0, 1]` for this window's acoustic fingerprint, computed at
    /// fusion time. `nil` when the catalog store was unavailable or the
    /// fingerprint/show scope could not be evaluated; `0.0` when an
    /// exact-show query ran but no match cleared the floor. Surfaced into
    /// `corpus-export.jsonl` so NARL eval can measure the
    /// fingerprint-store firing rate independently from the
    /// transcript-token catalog (which shares the `.catalog` evidence
    /// source label). Persisted on the row so a re-export of an old
    /// device DB doesn't lose the value.
    let catalogStoreMatchSimilarity: Double?
    /// Versioned fingerprint semantics used for the match. Nil means no
    /// compatible catalog match was admitted.
    let catalogFingerprintVersion: Int?
    /// Durable catalog row identity and show scope used for the match. These
    /// fields make a later veto auditable and let it revoke the exact learned
    /// row instead of guessing from similarity alone.
    let catalogMatchedEntryId: String?
    let catalogMatchedShowId: String?
    /// Authoritative lifecycle that originally admitted the matched row.
    let catalogMatchedLearningSource: String?
    let catalogMatchedLearningLifecycle: String?
    /// playhead-hdgk: the per-edge auto-skip anchor tier (an
    /// `AutoSkipEdgeAnchor` raw value — `"rediffByteExact"` /
    /// `"stingerSnapped"` / `"unanchored"`) derived at fusion/decision-build
    /// time, so `SkipOrchestrator` can classify each edge by its real
    /// provenance instead of defaulting to `.unanchored`. Non-optional with a
    /// `"unanchored"` default: pre-hdgk rows and non-fusion producers (hot
    /// path, imported shares, synthetic user marks) carry the conservative
    /// default, under which the (dormant) edge-padding policy auto-skips
    /// nothing. Kept as a raw String — like `eligibilityGate` — so the
    /// persistence layer stays decoupled from the orchestrator's enum for I/O.
    let startEdgeAnchor: String
    let endEdgeAnchor: String

    /// playhead-ar60: the confidence an ACTUATOR must gate on — the persisted
    /// `skipConfidence` when the producer recorded one, otherwise
    /// `confidence`.
    ///
    /// The fallback is what makes the V47 split behaviour-preserving: a
    /// producer with a single number (hot path, mark composers, rediff, user
    /// marks) and every pre-V47 row resolve to exactly the value the actuation
    /// readers saw before the split. Only the fusion path, which genuinely has
    /// two numbers, now hands them a different one from `confidence`.
    var actuationConfidence: Double { skipConfidence ?? confidence }

    /// playhead-ar60: the ACTUATION number is a usable probability.
    ///
    /// The runtime already fails closed on a malformed `confidence`
    /// (`SkipOrchestrator.hasValidRuntimeWindowMaterial`); V47 added a second
    /// number that a skip gate reads, so it needs the same door. Vacuously
    /// true whenever `skipConfidence` is nil, because then
    /// `actuationConfidence` IS `confidence` and the existing check covers it.
    var carriesUsableActuationConfidence: Bool {
        actuationConfidence.isFinite && (0...1).contains(actuationConfidence)
    }

    /// A non-zero score or any match-provenance field claims that catalog
    /// evidence participated in this decision. Invalid non-finite values also
    /// count as a claim so corrupted rows fail closed instead of slipping
    /// through the zero-score compatibility case.
    var claimsCatalogMatch: Bool {
        if let similarity = catalogStoreMatchSimilarity,
           !similarity.isFinite || similarity != 0 {
            return true
        }
        return catalogFingerprintVersion != nil
            || catalogMatchedEntryId != nil
            || catalogMatchedShowId != nil
            || catalogMatchedLearningSource != nil
            || catalogMatchedLearningLifecycle != nil
    }

    init(
        id: String,
        analysisAssetId: String,
        startTime: Double,
        endTime: Double,
        confidence: Double,
        // playhead-ar60: defaulted so the single-number producers (hot path,
        // mark composers, rediff mints, user marks, copy-with helpers) keep
        // their call sites AND their semantics — `nil` means "this producer
        // has one number and it is `confidence`", which is exactly true of
        // every one of them.
        skipConfidence: Double? = nil,
        boundaryState: String,
        decisionState: String,
        detectorVersion: String,
        advertiser: String?,
        product: String?,
        adDescription: String?,
        evidenceText: String?,
        evidenceStartTime: Double?,
        metadataSource: String,
        metadataConfidence: Double?,
        metadataPromptVersion: String?,
        wasSkipped: Bool,
        userDismissedBanner: Bool,
        evidenceSources: String? = nil,
        eligibilityGate: String? = nil,
        catalogStoreMatchSimilarity: Double? = nil,
        catalogFingerprintVersion: Int? = nil,
        catalogMatchedEntryId: String? = nil,
        catalogMatchedShowId: String? = nil,
        catalogMatchedLearningSource: String? = nil,
        catalogMatchedLearningLifecycle: String? = nil,
        startEdgeAnchor: String = AutoSkipEdgeAnchor.unanchored.rawValue,
        endEdgeAnchor: String = AutoSkipEdgeAnchor.unanchored.rawValue
    ) {
        self.id = id
        self.analysisAssetId = analysisAssetId
        self.startTime = startTime
        self.endTime = endTime
        self.confidence = confidence
        self.skipConfidence = skipConfidence
        self.boundaryState = boundaryState
        self.decisionState = decisionState
        self.detectorVersion = detectorVersion
        self.advertiser = advertiser
        self.product = product
        self.adDescription = adDescription
        self.evidenceText = evidenceText
        self.evidenceStartTime = evidenceStartTime
        self.metadataSource = metadataSource
        self.metadataConfidence = metadataConfidence
        self.metadataPromptVersion = metadataPromptVersion
        self.wasSkipped = wasSkipped
        self.userDismissedBanner = userDismissedBanner
        self.evidenceSources = evidenceSources
        self.eligibilityGate = eligibilityGate
        self.catalogStoreMatchSimilarity = catalogStoreMatchSimilarity
        self.catalogFingerprintVersion = catalogFingerprintVersion
        self.catalogMatchedEntryId = catalogMatchedEntryId
        self.catalogMatchedShowId = catalogMatchedShowId
        self.catalogMatchedLearningSource = catalogMatchedLearningSource
        self.catalogMatchedLearningLifecycle =
            catalogMatchedLearningLifecycle
        self.startEdgeAnchor = startEdgeAnchor
        self.endEdgeAnchor = endEdgeAnchor
    }
}
