#!/bin/bash
# playhead-9s1z MEASUREMENT ONLY.
# Extract, VERBATIM, the declarations SemanticSweepMarkComposer needs so the
# REAL composer source can be compiled into a macOS host harness. Nothing here
# is a re-implementation: every line below is copied out of the app target by
# line range, and `verify-deps.sh` re-extracts and diffs to prove it.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
OUT="$ROOT/tools/9s1z/Deps.swift"
P="$ROOT/Playhead"

{
  echo "// GENERATED by tools/9s1z/extract-deps.sh — DO NOT EDIT."
  echo "// Verbatim line-range extracts from the app target. playhead-9s1z, measurement only."
  echo "import Foundation"
  echo
  echo "// --- FoundationModelClassifier.swift 206-300 (inside the #else, non-FoundationModels branch)"
  sed -n '206,300p' "$P/Services/AdDetection/FoundationModelClassifier.swift"
  echo
  echo "// --- TranscriptSegmenter.swift 1-66 (AdTranscriptSegment + its two enums)"
  sed -n '1,66p' "$P/Services/AdDetection/TranscriptSegmenter.swift"
  echo
  echo "// --- TranscriptEngine.swift 19-167 (TranscriptWord, WeakAnchorPhrase, TranscriptWeakAnchorMetadata)"
  sed -n '19,167p' "$P/Services/TranscriptEngine/TranscriptEngine.swift"
  echo
  echo "// --- TranscriptEngine.swift 217-221 (TranscriptPassType)"
  sed -n '217,221p' "$P/Services/TranscriptEngine/TranscriptEngine.swift"
  echo
  echo "// --- SpanExtentSupport.swift 1-134 + 175 (the SpanExtentSupport struct;"
  echo "// --- 136-174 is derive(anchorProvenance:stingerTrace:), which reaches AnchorRef"
  echo "// --- and StingerRefinementTrace. The composer uses only \`.unanchored\`.)"
  sed -n '1,134p' "$P/Services/AdDetection/SpanExtentSupport.swift"
  sed -n '175p' "$P/Services/AdDetection/SpanExtentSupport.swift"
  echo
  echo "// --- EvidenceCatalogBuilder.swift 17-23 (EvidenceCategory)"
  sed -n '17,23p' "$P/Services/AdDetection/EvidenceCatalogBuilder.swift"
  echo
  echo "// --- AutoSkipEdgePadding.swift 135-146 (AutoSkipEdgeAnchor)"
  sed -n '135,146p' "$P/Services/SkipOrchestrator/AutoSkipEdgePadding.swift"
  echo
  echo "// --- EvidenceLedgerEntry.swift 17-101 (SkipEligibilityGate)"
  sed -n '17,101p' "$P/Services/AdDetection/EvidenceLedgerEntry.swift"
  echo
  echo "// --- AdDetectionService.swift 1427-1438 (AdDecisionState)"
  sed -n '1427,1438p' "$P/Services/AdDetection/AdDetectionService.swift"
  echo
  echo "// --- AnalysisStore.swift 332-387 (TranscriptChunk)"
  sed -n '332,387p' "$P/Persistence/AnalysisStore/AnalysisStore.swift"
  echo
  echo "// --- AnalysisStore.swift 389-508 + 542-609 (AdWindow; 509-541 is"
  echo "// --- hasCompatibleCatalogMatchProvenance, skipped: it reaches five catalog"
  echo "// --- types the composer never touches. Nothing else is omitted.)"
  sed -n '389,508p' "$P/Persistence/AnalysisStore/AnalysisStore.swift"
  sed -n '542,609p' "$P/Persistence/AnalysisStore/AnalysisStore.swift"
} | awk '
  # The line-range extracts each start at their file'"'"'s top, so they carry
  # their own `import` lines. Keep only the first one; a duplicate import is a
  # lint error and is not part of any declaration being copied.
  /^import / { if (seen[$0]++) next }
  { print }
' > "$OUT"
echo "wrote $OUT ($(wc -l < "$OUT") lines)"
