// EpisodeExecutionLease.swift
// playhead-uzdq: single-writer per-episode lease + append-only WorkJournal +
// global monotonic SchedulerEpoch.
//
// Why a lease? Analysis work for an episode can be dispatched from four
// distinct entry points — foreground assist, BGContinuedProcessingTask,
// BGProcessingTask, and URLSession delegate callbacks — all of which can
// fire concurrently. Without a single-writer abstraction the pipeline can
// double-process the same episode or race a finalize against a late
// callback. The lease is the low-level primitive that turns that free-for-
// all into a strict CAS: at any given moment at most one worker owns the
// analysis-jobs row for an episode, and every progress event flows through
// that owner's {generationID, schedulerEpoch} pair.
//
// Storage anchor: each `analysis_jobs` row IS the lease. The columns
// `leaseOwner`, `leaseExpiresAt`, `generationID`, and `schedulerEpoch` on
// that row carry the lease state. There is no separate
// `episode_execution_leases` table (see the bead spec, "No separate
// episode_execution_leases table").
//
// SchedulerEpoch (global, monotonic): stored as the singleton row
// `_meta(key='scheduler_epoch', value=Int)`. Bumped atomically by the
// coordinator when cross-episode scheduling changes (admissions,
// promotions, demotions) happen. Every lease acquisition captures the
// epoch into its row. A renewLease call with a stale epoch is rejected so
// late callbacks from pre-bump workers cannot write into a DB that the
// scheduler has since re-sorted.
//
// WorkJournal: append-only audit trail for every lease lifecycle event
// (acquired / checkpointed / preempted / finalized / failed). Journal
// rows are treated as `scratch` artifacts (see ``ArtifactClass``). The
// journal is the system of record for orphan recovery: on cold launch
// the coordinator inspects the last journal event per
// {episodeId, generationID} pair to decide whether a stranded lease is
// safe to resume (checkpointed) or needs to be discarded (already
// finalized/failed).

import Foundation

// MARK: - EpisodeExecutionLease

/// A live per-episode execution lease. Returned from
/// ``AnalysisCoordinator/acquireLease(episodeId:ownerWorkerId:schedulerEpoch:)``
/// and passed back by the owner on every renew/release call so the store
/// can reject stale callbacks.
///
/// Invariants held at acquisition time (enforced by the store under a
/// single SQLite transaction):
/// - `generationID` is a fresh UUID generated by the store; no two
///   concurrent leases on the same episode share a generation.
/// - `schedulerEpoch` matches the persisted `_meta.scheduler_epoch` at
///   the moment the lease was acquired.
/// - `expiresAt` > `acquiredAt` by the TTL requested by the caller.
struct EpisodeExecutionLease: Sendable, Equatable {
    let episodeId: String
    let ownerWorkerId: String
    let generationID: UUID
    let schedulerEpoch: Int
    let acquiredAt: Double
    let expiresAt: Double

    /// Last known checkpoint captured by the owner — nil when the lease
    /// was acquired freshly (no prior progress) or when the owner has
    /// not yet checkpointed. Updated by callers via
    /// ``AnalysisCoordinator/renewLease(_:)`` when they want the store
    /// to persist resumable progress.
    ///
    /// NOTE: persistence of the checkpoint itself reuses
    /// ``AnalysisStore/persistFeatureExtractionCheckpoint(_:)`` on the
    /// feature_extraction_state table — this field only carries the
    /// most-recent checkpoint through the lease struct so callers don't
    /// have to round-trip the store on each renewal.
    let currentCheckpoint: FeatureExtractionCheckpoint?

    /// Signal from the coordinator to the owner that a higher-priority
    /// demand has arrived. Owners poll this at shard boundaries and
    /// release with `.preempted` when true. Not persisted — lives in
    /// memory only for the duration of the lease.
    var preemptionRequested: Bool
}

// MARK: - WorkJournalEntry

/// An append-only record of a single lease lifecycle event. Persisted
/// into the `work_journal` table, which is indexed by
/// `(episode_id, generation_id)` for fast "last event for this
/// generation" lookups during orphan recovery.
///
/// All WorkJournal rows are classified as ``ArtifactClass/scratch`` —
/// they are reconstructible audit metadata, never user-facing media,
/// and safe to evict under dual-cap pressure (per playhead-h7r).
struct WorkJournalEntry: Sendable, Equatable {
    /// Lifecycle events a lease can emit. Stored as the `event_type`
    /// column's raw string value.
    enum EventType: String, Sendable, Hashable, CaseIterable {
        /// Lease was acquired for this {episode, generation}. Exactly
        /// one `acquired` entry exists per generation.
        case acquired

        /// Owner persisted a resumable checkpoint. Multiple
        /// `checkpointed` entries may appear per generation.
        case checkpointed

        /// Owner released the lease because a higher-priority demand
        /// pre-empted it. The row's `cause` is typically non-nil and
        /// carries the reason (playhead-1nl6 will enrich the taxonomy).
        case preempted

        /// Owner released the lease after successfully completing
        /// the work. At most one `finalized` entry per generation;
        /// `releaseLease(finalized)` is idempotent — a second call is
        /// a no-op.
        case finalized

        /// Owner released the lease after a non-recoverable error.
        /// `cause` carries the reason; attempt count is NOT
        /// auto-incremented by the journal append — callers that want
        /// retry semantics drive that separately.
        case failed
    }

    let id: String
    let episodeId: String
    let generationID: UUID
    let schedulerEpoch: Int
    let timestamp: Double
    let eventType: EventType

    /// Reason code for a release event. `nil` for success events
    /// (`acquired`, `checkpointed`, `finalized`). `preempted` and
    /// `failed` typically carry a cause.
    ///
    /// EMISSION CHANNEL for playhead-1nl6: when 1nl6 extends
    /// ``InternalMissCause`` with the full cause taxonomy, every
    /// journal row is a canonical emission site. 1nl6 will read these
    /// rows to build its InternalMiss telemetry stream.
    let cause: InternalMissCause?

    /// JSON blob for caller-specific context. Must be valid JSON; the
    /// store does not parse it. Default is `{}`.
    let metadata: String

    /// Always `.scratch` for WorkJournal rows (see file header).
    let artifactClass: ArtifactClass
}

// MARK: - InternalMissCause (reused from CauseTaxonomy.swift)
//
// The WorkJournal's `cause` column stores the raw value of
// ``InternalMissCause``, which is defined in
// `CauseTaxonomy.swift`. That enum already carries the full 16-row
// cause taxonomy that playhead-1nl6 is built around, so this file
// does NOT declare its own copy. The journal is the canonical
// emission site: every release event persists the raw string of the
// caller's `InternalMissCause?`, and playhead-1nl6 will consume those
// rows to build its telemetry stream.

// MARK: - Errors

/// Errors raised by lease acquisition / renewal / release paths.
enum LeaseError: Error, CustomStringConvertible, Equatable {
    /// Another worker already holds a live lease on this episode. Caller
    /// should back off or enqueue the request for after the current
    /// holder's release.
    case leaseHeld(episodeId: String)

    /// The caller's `schedulerEpoch` is older than the store's current
    /// epoch. Typically seen by a worker that captured an epoch before
    /// a cross-episode promotion/demotion ran. Caller should treat its
    /// in-flight work as stale and reacquire.
    case staleEpoch(expected: Int, actual: Int)

    /// The caller's `generationID` does not match the row's current
    /// generation. Typically seen when a late callback fires after the
    /// lease has already been released or transferred. Treated as a
    /// no-op at the API boundary — the WorkJournal still records the
    /// attempt for audit.
    ///
    /// **Overloaded semantics (tech debt).** This case is ALSO thrown
    /// from renewal-time expiry checks — i.e. when the caller's
    /// generation is correct but the lease has already passed its
    /// deadline and been reclaimed. The underlying SQL predicate
    /// conflates "no row with matching generation" and "no row with
    /// matching generation AND unexpired deadline", so the callsite
    /// throws the same error for both conditions. From the caller's
    /// perspective both mean "your lease is no longer valid; stop", but
    /// a future refactor should split this into `.generationMismatch`
    /// vs. `.leaseExpired` so log diagnostics can distinguish late
    /// callbacks from deadline-miss reclaim cycles.
    case generationMismatch(episodeId: String)

    /// No analysis_jobs row exists for this episode, so there is
    /// nothing to lease. The caller must enqueue a job first. This is
    /// distinct from ``leaseHeld`` so orchestration code can decide
    /// whether to wait (leaseHeld) vs. produce more work (no row).
    case noJobForEpisode(episodeId: String)

    var description: String {
        switch self {
        case .leaseHeld(let id): "Lease already held for episode \(id)"
        case .staleEpoch(let expected, let actual):
            "Stale scheduler epoch: caller=\(expected), current=\(actual)"
        case .generationMismatch(let id):
            "Generation ID mismatch for episode \(id)"
        case .noJobForEpisode(let id):
            "No analysis_jobs row for episode \(id); enqueue first"
        }
    }
}
