// StingerRefinerTests.swift
// playhead-l2f.6 / playhead-xsdz.38: unit tests for the pure
// stinger-refinement logic on synthetic envelopes. No audio, no actor, no
// bundle — every case hands the refiner hand-built 50 Hz envelopes and
// asserts the snap/gate/cap/revert/joint-pair contracts documented on
// `StingerRefiner`.
//
// v4 (xsdz.38): the refiner is the production port of the offline JOINT
// candidate-pair oracle (`refine_edges_joint`, commit 5dc1b961). The tests
// here split in two:
//   • the original l2f.6 suites, updated where the v3 → v4 contract
//     intentionally changed (one-edge grid-set is REPLACED by joint pairs;
//     guard tests — gate/move-cap/revert/end>start — keep equivalent or
//     stronger assertions);
//   • `JointOracleParityTests`, planted-envelope port-fidelity scenarios
//     whose expected outcomes were generated by RUNNING the python oracle
//     with default `JointConfig` on mirrored worlds (see the per-test
//     oracle transcripts in the comments).

import Foundation
import Testing
@testable import Playhead

@Suite("StingerRefiner (playhead-l2f.6, v4 joint playhead-xsdz.38)")
struct StingerRefinerTests {

    // MARK: - Synthetic fixtures

    /// Deterministic pseudo-random template values in [0, 3] (seeded LCG —
    /// stable across runs and platforms). Shaped like a log-RMS envelope.
    private static func syntheticTemplate(count: Int = 350, seed: UInt64 = 9) -> [Float] {
        var state = seed
        return (0..<count).map { _ in
            state = state &* 6_364_136_223_846_793_005 &+ 1_442_695_040_888_963_407
            return Float(state >> 40) / Float(1 << 24) * 3.0
        }
    }

    /// A quiet target envelope with `template` planted at `offset`.
    /// Quiet-floor frames are constant, so their centered correlation with
    /// the template is ~0 and the planted copy is the unambiguous peak
    /// (NCC exactly 1.0 up to floating-point noise).
    private static func envelope(
        planting template: [Float],
        at offset: Int,
        totalFrames: Int,
        startSeconds: Double
    ) -> StingerSearchEnvelope {
        var values = [Float](repeating: 0.05, count: totalFrames)
        for (i, v) in template.enumerated() {
            values[offset + i] = v
        }
        return StingerSearchEnvelope(values: values, startSeconds: startSeconds)
    }

    private static func entry(
        pre: StingerTemplate? = nil,
        post: StingerTemplate? = nil,
        grid: Double? = nil,
        gridMaxMultiple: Int? = nil
    ) -> StingerShowEntry {
        StingerShowEntry(
            showKeys: ["test-show"],
            showName: "Test Show",
            pre: pre,
            post: post,
            podWidthGridSeconds: grid,
            gridMaxPodMultiple: gridMaxMultiple
        )
    }

    private static func template(
        _ values: [Float],
        edgeIndex: Int,
        offsetSeconds: Double = 0,
        confidence: Double = 0.80
    ) -> StingerTemplate {
        StingerTemplate(
            template: values,
            edgeSampleIndex: edgeIndex,
            edgeOffsetSeconds: offsetSeconds,
            confidence: confidence,
            support: 3
        )
    }

    // MARK: - Successful snap

    @Test("Planted template snaps the start edge to the exact learned position")
    func successfulSnapToPlantedTemplate() throws {
        let values = Self.syntheticTemplate()
        // Plant at frame 700 of an envelope anchored at 0s: edge index 300
        // → snapped = (700 + 300)/50 + 0.5s learned offset = 20.5s.
        let pre = Self.template(values, edgeIndex: 300, offsetSeconds: 0.5, confidence: 0.80)
        let envelope = Self.envelope(planting: values, at: 700, totalFrames: 9000, startSeconds: 0)

        let result = StingerRefiner.refine(
            proposalStart: 30.0,
            proposalEnd: 60.0,
            entry: Self.entry(pre: pre),
            startEnvelope: envelope,
            endEnvelope: nil,
            episodeDuration: 600.0
        )

        #expect(abs(result.startTime - 20.5) < 0.001, "snap must land on the planted edge (got \(result.startTime))")
        #expect(result.endTime == 60.0, "end edge has no post template and must not move")
        #expect(result.trace.startSnapped)
        #expect(!result.trace.endSnapped)
        #expect(!result.trace.gridApplied)
        #expect(!result.trace.revertedNoOverlap)
        let peak = try #require(result.trace.startPeak)
        #expect(peak > 0.99, "planted copy must correlate at ~1.0 (got \(peak))")
        let delta = try #require(result.trace.startDeltaSeconds)
        #expect(abs(delta - (-9.5)) < 0.001)
        #expect(result.trace.endDeltaSeconds == nil)
        // v4 joint trace: the planted copy is the ONLY qualifying maximum;
        // the end edge has no template so no candidates and no count.
        #expect(result.trace.startCandidateCount == 1)
        #expect(result.trace.endCandidateCount == nil)
        let pairScore = try #require(result.trace.pairScore)
        // peak (~1.0) − 1e-4 · 9.5 movement; no grid terms.
        #expect(abs(pairScore - (1.0 - 1e-4 * 9.5)) < 0.01)
        #expect(result.trace.gridTermApplied == nil)
    }

    @Test("No envelope (no PCM available) means the side cannot snap")
    func noEnvelopeMeansNoSnap() {
        let values = Self.syntheticTemplate()
        let pre = Self.template(values, edgeIndex: 300)
        let result = StingerRefiner.refine(
            proposalStart: 30.0,
            proposalEnd: 60.0,
            entry: Self.entry(pre: pre),
            startEnvelope: nil,
            endEnvelope: nil,
            episodeDuration: 600.0
        )
        #expect(result.startTime == 30.0)
        #expect(result.endTime == 60.0)
        #expect(result.trace == StingerRefinementTrace())
    }

    // MARK: - Gate rejection

    @Test("Per-show confidence gate rejects a degraded match that a low-confidence show would accept")
    func gateRejectionBelowConfidence() throws {
        let values = Self.syntheticTemplate()
        // Degrade the planted copy: flatten its second half to the mean so
        // the correlation is genuinely partial. Pre-flight the resulting
        // peak into the (0.50 + margin, 0.85 − margin) band so both arms
        // of the assertion are meaningful rather than magic constants.
        let mean = values.reduce(0, +) / Float(values.count)
        var degraded = values
        for i in (values.count / 2)..<values.count {
            degraded[i] = mean
        }
        let envelope = Self.envelope(planting: degraded, at: 700, totalFrames: 9000, startSeconds: 0)
        let measured = try #require(StingerRefiner.normalizedCrossCorrelationPeak(
            template: values,
            target: envelope.values
        ))
        try #require(measured.peak > 0.55 && measured.peak < 0.80,
                     "fixture must land between the two gates (got \(measured.peak))")

        // Arm 1: confidence 1.0 → gate max(0.50, 0.85) = 0.85 → REJECT.
        let strict = StingerRefiner.refine(
            proposalStart: 30.0,
            proposalEnd: 60.0,
            entry: Self.entry(pre: Self.template(values, edgeIndex: 300, confidence: 1.0)),
            startEnvelope: envelope,
            endEnvelope: nil,
            episodeDuration: 600.0
        )
        #expect(!strict.trace.startSnapped, "peak \(measured.peak) must not clear the 0.85 gate")
        #expect(strict.startTime == 30.0)
        #expect(strict.trace.startPeak == nil, "rejected matches record no peak (mirrors the offline trace)")
        #expect(strict.trace.startCandidateCount == nil, "gate rejection happens at candidate enumeration — zero candidates")

        // Arm 2: confidence 0.60 → gate max(0.50, 0.45) = 0.50 → ACCEPT.
        // Pins the floor half of `max(0.50, confidence − 0.15)`.
        let loose = StingerRefiner.refine(
            proposalStart: 30.0,
            proposalEnd: 60.0,
            entry: Self.entry(pre: Self.template(values, edgeIndex: 300, confidence: 0.60)),
            startEnvelope: envelope,
            endEnvelope: nil,
            episodeDuration: 600.0
        )
        #expect(loose.trace.startSnapped, "the same peak must clear the 0.50 floor gate")
    }

    // MARK: - Move cap

    @Test("Snaps moving an edge farther than 75s are refused")
    func moveCapRejection() {
        let values = Self.syntheticTemplate()
        // Planted edge at 20.0s, proposal start at 130.0s → 110s move.
        let pre = Self.template(values, edgeIndex: 300)
        let envelope = Self.envelope(planting: values, at: 700, totalFrames: 9500, startSeconds: 0)
        let result = StingerRefiner.refine(
            proposalStart: 130.0,
            proposalEnd: 160.0,
            entry: Self.entry(pre: pre),
            startEnvelope: envelope,
            endEnvelope: nil,
            episodeDuration: 600.0
        )
        #expect(!result.trace.startSnapped, "a 110s move must be refused by the 75s cap")
        #expect(result.startTime == 130.0)
        #expect(result.endTime == 160.0)
        #expect(result.trace.startCandidateCount == nil, "the cap excludes the candidate at enumeration time")
        #expect(result.trace == StingerRefinementTrace(), "nothing consulted-and-qualifying ⇒ pristine trace")
    }

    // MARK: - Overlap guard (pair feasibility + revert belt-and-braces)

    @Test("A pair that abandons overlap is infeasible; joint picks the overlap-preserving snap instead")
    func pairFeasibilityRejectsOverlapAbandoningPair() throws {
        // v3 → v4 DELIBERATE contract change (oracle parity, X5): the v3
        // recipe snapped both edges to [20, 25], noticed the zero overlap
        // against the [80, 95] proposal, and reverted BOTH edges. The
        // joint recipe never builds that window: the (20, 25) pair is
        // infeasible at enumeration, and the best FEASIBLE pair keeps the
        // start snap while leaving the end on the proposal.
        // Oracle (refine_edges_joint, defaults): [80, 95] → [20, 95],
        // start_kind=peak, end_kind=none, pair_score 0.994.
        let preValues = Self.syntheticTemplate(seed: 11)
        let postValues = Self.syntheticTemplate(seed: 23)
        let pre = Self.template(preValues, edgeIndex: 300)
        let post = Self.template(postValues, edgeIndex: 50)
        let startEnvelope = Self.envelope(planting: preValues, at: 700, totalFrames: 9000, startSeconds: 0)
        let endEnvelope = Self.envelope(planting: postValues, at: 1200, totalFrames: 9000, startSeconds: 0)

        let result = StingerRefiner.refine(
            proposalStart: 80.0,
            proposalEnd: 95.0,
            entry: Self.entry(pre: pre, post: post),
            startEnvelope: startEnvelope,
            endEnvelope: endEnvelope,
            episodeDuration: 600.0
        )

        #expect(abs(result.startTime - 20.0) < 0.001, "the feasible pair keeps the start snap (got \(result.startTime))")
        #expect(result.endTime == 95.0, "the end candidate at 25.0 would abandon overlap — the end must stay on the proposal")
        #expect(!result.trace.revertedNoOverlap)
        #expect(result.trace.startSnapped)
        #expect(!result.trace.endSnapped)
        // The invariant the old revert test protected, stated directly:
        // the refined window ALWAYS overlaps the proposal.
        #expect(min(result.endTime, 95.0) - max(result.startTime, 80.0) > 0,
                "refinement must never abandon the presence evidence")
        let pairScore = try #require(result.trace.pairScore)
        #expect(abs(pairScore - 0.994) < 0.01, "oracle pair_score 0.994 (peak ~1.0 − 1e-4·60)")
    }

    @Test("The clamp-level revert guard still reverts both edges when clamping abandons overlap")
    func revertGuardWhenClampingAbandonsOverlap() {
        // Belt-and-braces (same as the oracle's final overlap check): pair
        // feasibility guarantees raw-pair overlap, but an out-of-range
        // proposal (beyond the episode) gets pulled back by the episode
        // clamps — [650, 660] with duration 600 clamps to [599, 600],
        // which no longer overlaps. BOTH edges must revert.
        let values = Self.syntheticTemplate()
        let pre = Self.template(values, edgeIndex: 300)
        let result = StingerRefiner.refine(
            proposalStart: 650.0,
            proposalEnd: 660.0,
            entry: Self.entry(pre: pre),
            startEnvelope: nil,
            endEnvelope: nil,
            episodeDuration: 600.0
        )
        #expect(result.startTime == 650.0, "revert guard must restore the proposal start")
        #expect(result.endTime == 660.0, "revert guard must restore the proposal end")
        #expect(result.trace.revertedNoOverlap)
        #expect(!result.trace.startSnapped, "revert clears the snap flags")
        #expect(!result.trace.endSnapped, "revert clears the snap flags")
        #expect(!result.trace.gridApplied)
        #expect(result.trace.startDeltaSeconds == nil)
        #expect(result.trace.endDeltaSeconds == nil)
    }

    // MARK: - Grid (v4: derived candidates + pair scoring)

    @Test("A confident lone snap earns a grid-derived partner on the other edge")
    func gridApplicationWhenOneEdgeSnaps() throws {
        let values = Self.syntheticTemplate()
        // Snap start to 5 + (4200 + 300)/50 = 95.0s; proposal [100, 152].
        // v4: the confident (≥ 0.65) start anchor derives end candidates
        // at 95 + k·30; the on-grid (95, 155) pair earns the 0.5 bonus and
        // beats both the (95, 125) pair (more end movement) and the
        // no-partner (95, 152) pair (width 57 is within grid tolerance but
        // the untouched proposal edge is out of bonus scope).
        // Oracle X2 (0.9-cosine plant): [100, 152] → [95, 155],
        // end_kind=derived, grid_applied — same winning pair as this
        // fixture, whose exact-copy plant (NCC ≈ 1.0) scores
        // ~1.0 + 0.5 − 1e-4·8 ≈ 1.4992 (the oracle world's 0.9 peak
        // scores 1.3992; only the peak term differs).
        let pre = Self.template(values, edgeIndex: 300)
        let envelope = Self.envelope(planting: values, at: 4200, totalFrames: 9000, startSeconds: 5.0)
        let result = StingerRefiner.refine(
            proposalStart: 100.0,
            proposalEnd: 152.0,
            entry: Self.entry(pre: pre, grid: 30.0),
            startEnvelope: envelope,
            endEnvelope: nil,
            episodeDuration: 600.0
        )
        #expect(abs(result.startTime - 95.0) < 0.001, "got \(result.startTime)")
        #expect(abs(result.endTime - 155.0) < 0.001, "the derived on-grid partner must set end = start + 60 (got \(result.endTime))")
        #expect(result.trace.startSnapped)
        #expect(!result.trace.endSnapped)
        #expect(result.trace.gridApplied, "a derived candidate on the end edge reports gridApplied")
        let endDelta = try #require(result.trace.endDeltaSeconds)
        #expect(abs(endDelta - 3.0) < 0.001)
        #expect(result.trace.startCandidateCount == 1)
        // Derived ends at 125/155/185/215 honor the move cap (245 is 93s
        // from the proposal end and must be excluded).
        #expect(result.trace.endCandidateCount == 4)
        #expect(result.trace.gridTermApplied == "bonus")
        let pairScore = try #require(result.trace.pairScore)
        #expect(abs(pairScore - 1.4992) < 0.01, "peak ~1.0 + 0.5 bonus − 1e-4·8 movement")
    }

    @Test("A sub-grid width earns a derived partner one full grid away")
    func gridMinimumPositiveMultiple() {
        let values = Self.syntheticTemplate()
        // Snap start to 95.0s; proposal [100, 104]. The nearest derived
        // partner (95 + 30 = 125) wins on the movement tie-break over
        // 95 + 60 = 155 (equal on-grid bonus, more movement).
        // Oracle X3 (0.9-cosine plant): [100, 104] → [95, 125] — same
        // winning pair as this fixture's exact-copy plant (whose score is
        // higher by the 0.1 peak delta).
        let pre = Self.template(values, edgeIndex: 300)
        let envelope = Self.envelope(planting: values, at: 4200, totalFrames: 9000, startSeconds: 5.0)
        let result = StingerRefiner.refine(
            proposalStart: 100.0,
            proposalEnd: 104.0,
            entry: Self.entry(pre: pre, grid: 30.0),
            startEnvelope: envelope,
            endEnvelope: nil,
            episodeDuration: 600.0
        )
        #expect(abs(result.startTime - 95.0) < 0.001)
        #expect(abs(result.endTime - 125.0) < 0.001, "the nearest on-grid derived partner must win (got \(result.endTime))")
        #expect(result.trace.gridApplied)
        #expect(result.trace.gridTermApplied == "bonus")
    }

    @Test("Exact score ties resolve through the oracle's (score, -moved, start, end) key — later end wins")
    func jointKeyOrderingResolvesExactTies() {
        let values = Self.syntheticTemplate()
        // Snap start to 95.0s; proposal [100, 170]. Derived partners at
        // 155 (2×30) and 185 (3×30) are EXACTLY symmetric around the
        // proposal end: identical bonus, identical movement (15s), same
        // start — a bitwise score tie. The oracle's strict lexicographic
        // key comparison then prefers the larger end time. This pins the
        // port's iteration-order/tie parity (a `>=` in the wrong place or
        // a reordered candidate list would flip it to 155).
        // Oracle X1 (0.9-cosine plant): [100, 170] → [95, 185] — same
        // tie, same resolution as this fixture's exact-copy plant.
        let pre = Self.template(values, edgeIndex: 300)
        let envelope = Self.envelope(planting: values, at: 4200, totalFrames: 9000, startSeconds: 5.0)
        let result = StingerRefiner.refine(
            proposalStart: 100.0,
            proposalEnd: 170.0,
            entry: Self.entry(pre: pre, grid: 30.0),
            startEnvelope: envelope,
            endEnvelope: nil,
            episodeDuration: 600.0
        )
        #expect(abs(result.startTime - 95.0) < 0.001)
        #expect(
            abs(result.endTime - 185.0) < 0.001,
            "the exact tie must resolve to the larger end time like the oracle (got \(result.endTime))"
        )
        #expect(result.trace.gridApplied)
    }

    @Test("Derived candidates require a confident anchor peak (the 0.65 gate)")
    func gridRequiresConfidentAnchorPeak() throws {
        // The v2 production lesson in joint form (xsdz.38 sweep finding 4:
        // lowering the derived-anchor gate to 0.50 lets the eat peak
        // derive its own on-grid partner and the content eat returns).
        // Blend the planted copy with a decorrelated signal so the snap
        // peak lands in [gate, gridMinimumPeak) — the snap is accepted but
        // it derives NO partner candidates. The two-arm #require
        // pre-flight keeps the fixture honest if constants ever move.
        let values = Self.syntheticTemplate()
        // Independent PRNG stream => near-zero correlation with `values`;
        // 0.6/0.8 amplitudes put the NCC peak near 0.60 — inside
        // [snap gate 0.50, grid floor 0.65).
        let noise = Self.syntheticTemplate(seed: 77)
        let blended = zip(values, noise).map { 0.6 * $0 + 0.8 * $1 }
        let pre = Self.template(values, edgeIndex: 300, confidence: 0.65) // gate = 0.50
        let envelope = Self.envelope(planting: blended, at: 4200, totalFrames: 9000, startSeconds: 5.0)

        let probe = StingerRefiner.refine(
            proposalStart: 100.0,
            proposalEnd: 152.0,
            entry: Self.entry(pre: pre),
            startEnvelope: envelope,
            endEnvelope: nil,
            episodeDuration: 600.0
        )
        let peak = try #require(probe.trace.startPeak, "fixture must still clear the snap gate")
        try #require(peak < StingerRefiner.gridMinimumPeak, "fixture peak must sit below the grid floor (got \(peak))")

        let result = StingerRefiner.refine(
            proposalStart: 100.0,
            proposalEnd: 152.0,
            entry: Self.entry(pre: pre, grid: 30.0),
            startEnvelope: envelope,
            endEnvelope: nil,
            episodeDuration: 600.0
        )
        #expect(result.trace.startSnapped, "snap itself stays accepted")
        #expect(!result.trace.gridApplied, "a sub-floor anchor peak must derive nothing")
        #expect(abs(result.endTime - 152.0) < 0.001, "unsnapped edge must stay at the proposal")
        #expect(result.trace.endCandidateCount == nil, "no post template + no derived ⇒ zero end candidates")
        #expect(result.trace.gridTermApplied == nil, "the (peak, proposal-edge) pair is out of bonus scope")
    }

    @Test("A large-grid off-grid widening pays the inconsistency penalty and the snap is refused outright")
    func offGridWideningPenaltyRefusesLoneSnap() throws {
        // v3 → v4 DELIBERATE contract change (this fixture was v3's
        // "grid-adjusted edge honors the move cap"): with a 200s grid the
        // lone start snap to 95.0 leaves a width of 11.5s sitting 188.5s
        // from the 1×200 pod while widening 5s, so the eat-killer product
        // term (0.08 · 188.5 · 5 / 75 ≈ 1.005) drives the pair below the
        // no-snap floor — the snap is refused ENTIRELY, not just the grid
        // adjustment. Derived candidates are structurally absent too: one
        // grid step (200s) exceeds the 165s search reach.
        // Oracle X4: [100, 106.5] → [100, 106.5], pair_score 0.0.
        let values = Self.syntheticTemplate()
        let pre = Self.template(values, edgeIndex: 300)
        let envelope = Self.envelope(planting: values, at: 4200, totalFrames: 9000, startSeconds: 5.0)
        let result = StingerRefiner.refine(
            proposalStart: 100.0,
            proposalEnd: 106.5,
            entry: Self.entry(pre: pre, grid: 200.0),
            startEnvelope: envelope,
            endEnvelope: nil,
            episodeDuration: 600.0
        )
        #expect(result.startTime == 100.0, "the penalized snap must lose to the no-snap floor")
        #expect(result.endTime == 106.5)
        #expect(!result.trace.startSnapped)
        #expect(!result.trace.gridApplied)
        #expect(result.trace.startCandidateCount == 1, "the qualifying peak was enumerated — it lost on score")
        #expect(result.trace.endCandidateCount == nil, "grid step 200s exceeds the 165s derived reach")
        let pairScore = try #require(result.trace.pairScore)
        #expect(pairScore == 0.0, "the winning pair is the no-snap floor")
    }

    @Test("Both edges snapping to an on-grid-within-tolerance width earn the pair bonus, no derived candidate")
    func gridBonusWhenBothEdgesSnap() {
        let preValues = Self.syntheticTemplate(seed: 11)
        let postValues = Self.syntheticTemplate(seed: 23)
        // Pre → 95.0s, post → 152.0s: width 57 sits 3.0s from the 60s pod
        // — exactly ON the grid tolerance boundary, so the both-peaks pair
        // takes the 0.5 bonus and dominates every derived alternative.
        // Both bounds equal the v3 outcome; the trace now explains it as a
        // bonused peak pair (v3 asserted "grid skipped when both snap").
        // Oracle X7: [100, 150] → [95, 152], pair_score 2.4993,
        // grid_applied false.
        let pre = Self.template(preValues, edgeIndex: 300)
        let post = Self.template(postValues, edgeIndex: 50)
        let startEnvelope = Self.envelope(planting: preValues, at: 4200, totalFrames: 9000, startSeconds: 5.0)
        let endEnvelope = Self.envelope(planting: postValues, at: 7300, totalFrames: 9000, startSeconds: 5.0)
        let result = StingerRefiner.refine(
            proposalStart: 100.0,
            proposalEnd: 150.0,
            entry: Self.entry(pre: pre, post: post, grid: 30.0),
            startEnvelope: startEnvelope,
            endEnvelope: endEnvelope,
            episodeDuration: 600.0
        )
        #expect(result.trace.startSnapped)
        #expect(result.trace.endSnapped)
        #expect(!result.trace.gridApplied, "no derived candidate in the winning pair")
        #expect(result.trace.gridTermApplied == "bonus")
        #expect(abs(result.startTime - 95.0) < 0.001)
        #expect(abs(result.endTime - 152.0) < 0.001)
    }

    // MARK: - end <= start impossibility

    @Test("A post candidate landing before the start edge is infeasible — the proposal survives untouched")
    func endLEStartImpossibility() {
        let values = Self.syntheticTemplate()
        // Post template planted so the candidate END = 10.0s, far BEFORE
        // the 50.0s proposal start (move 50s, within the cap). v4 rejects
        // the inverted pair at enumeration (width < 1s ⇒ infeasible), so
        // the proposal survives byte-identical — strictly stronger than
        // v3's clamp-rescue, and exactly the oracle's behavior.
        // Oracle X6: [50, 60] → [50, 60], pair_score 0.0.
        let post = Self.template(values, edgeIndex: 50)
        let envelope = Self.envelope(planting: values, at: 450, totalFrames: 9000, startSeconds: 0)
        let result = StingerRefiner.refine(
            proposalStart: 50.0,
            proposalEnd: 60.0,
            entry: Self.entry(post: post),
            startEnvelope: nil,
            endEnvelope: envelope,
            episodeDuration: 600.0
        )
        #expect(result.startTime == 50.0, "the inverted pair is infeasible — start must not move")
        #expect(result.endTime == 60.0, "the inverted pair is infeasible — end must not move")
        #expect(!result.trace.endSnapped)
        #expect(result.endTime > result.startTime, "end <= start must be impossible (got [\(result.startTime), \(result.endTime)])")
    }

    @Test("Refined bounds always satisfy end > start across adversarial snap/grid combinations")
    func endAlwaysExceedsStartAcrossAdversarialCombinations() {
        let values = Self.syntheticTemplate()
        let envelope = Self.envelope(planting: values, at: 450, totalFrames: 9000, startSeconds: 0)
        // Sweep proposals (including near-zero and near-duration windows)
        // against pre-only / post-only / both / gridded entries. Every
        // output must keep end > start — the structural invariant the
        // wire-in relies on before handing bounds to fusion.
        let entries: [StingerShowEntry] = [
            Self.entry(pre: Self.template(values, edgeIndex: 300)),
            Self.entry(post: Self.template(values, edgeIndex: 50)),
            Self.entry(
                pre: Self.template(values, edgeIndex: 300),
                post: Self.template(values, edgeIndex: 50),
                grid: 30.0
            ),
            Self.entry(pre: Self.template(values, edgeIndex: 300), grid: 30.0),
        ]
        let proposals: [(Double, Double)] = [
            (0.5, 2.0), (10.0, 11.5), (50.0, 60.0), (0.0, 90.0),
            (598.0, 599.5), (14.0, 15.0),
        ]
        for entry in entries {
            for (start, end) in proposals {
                let result = StingerRefiner.refine(
                    proposalStart: start,
                    proposalEnd: end,
                    entry: entry,
                    startEnvelope: envelope,
                    endEnvelope: envelope,
                    episodeDuration: 600.0
                )
                #expect(
                    result.endTime > result.startTime,
                    "inverted window for proposal [\(start), \(end)] entry sides pre=\(entry.pre != nil) post=\(entry.post != nil) grid=\(entry.podWidthGridSeconds != nil): got [\(result.startTime), \(result.endTime)]"
                )
            }
        }
    }

    // MARK: - NCC guards

    @Test("NCC refuses sub-second templates, oversized templates, and zero-variance templates")
    func nccGuards() {
        let target = [Float](repeating: 0.5, count: 500)
        // Sub-second template (< 50 frames).
        #expect(StingerRefiner.normalizedCrossCorrelationPeak(
            template: [Float](repeating: 1, count: 49),
            target: target
        ) == nil)
        // Template longer than the target.
        #expect(StingerRefiner.normalizedCrossCorrelationPeak(
            template: [Float](repeating: 1, count: 501),
            target: target
        ) == nil)
        // Zero-variance template has no defined correlation.
        #expect(StingerRefiner.normalizedCrossCorrelationPeak(
            template: [Float](repeating: 1, count: 350),
            target: target
        ) == nil)
    }

    @Test("nccQualifyingMaxima gates, reports plateau right edges, and admits endpoints")
    func nccQualifyingMaximaContract() {
        // Direct port of the oracle's `ncc_qualifying_maxima` unit tests.
        let curve = [0.1, 0.6, 0.55, 0.7, 0.7, 0.4]
        let gated = StingerRefiner.nccQualifyingMaxima(curve: curve, gate: 0.5)
        #expect(gated.map(\.index) == [1, 4], "plateaus report their right edge")
        #expect(gated.map(\.value) == [0.6, 0.7])
        let strict = StingerRefiner.nccQualifyingMaxima(curve: curve, gate: 0.65)
        #expect(strict.map(\.index) == [4])

        #expect(StingerRefiner.nccQualifyingMaxima(curve: [0.8, 0.2], gate: 0.5).map(\.index) == [0])
        #expect(StingerRefiner.nccQualifyingMaxima(curve: [0.2, 0.8], gate: 0.5).map(\.index) == [1])
    }

    // MARK: - Joint oracle parity (playhead-xsdz.38)
    //
    // Port-fidelity scenarios: synthetic candidate worlds built with the
    // SAME exact-cosine planting the oracle's test harness uses
    // (scripts/tests/test_l2f_stinger_joint.py `PlantedEnvelopes`) — the
    // planted signal is `cos·û + sin·n̂ + 2.0` around the centered,
    // normalized template, so the NCC at the plant is EXACTLY the chosen
    // cosine and every score in a scenario is hand-computable. Expected
    // outcomes below were generated by RUNNING `refine_edges_joint`
    // (commit 5dc1b961) with default `JointConfig` on mirrored worlds;
    // each test quotes the oracle's output. The noise realizations differ
    // between python and Swift, but the planted cosines are exact in
    // both, so every DECISION margin is untouched by noise. Honest margin
    // note: against a 100-frame template the background NCC has σ ≈ 0.1,
    // so its maximum over a ±90s span sits around ~0.43 — the 0.50 gate
    // clears it by a modest ~0.07. The seeds are deterministic, so the
    // candidate-count assertions are stable, but a re-rolled noise world
    // (new seed / different Box-Muller libm) could need re-pinning of
    // counts; the chosen bounds and scores would not move.

    /// Deterministic standard normals: seeded LCG uniforms + Box-Muller.
    private struct SeededGaussians {
        private var state: UInt64
        private var cached: Double?

        init(seed: UInt64) {
            state = seed &+ 0x9E37_79B9_7F4A_7C15
        }

        private mutating func uniform() -> Double {
            state = state &* 6_364_136_223_846_793_005 &+ 1_442_695_040_888_963_407
            return Double(state >> 11) * 0x1.0p-53
        }

        mutating func next() -> Double {
            if let value = cached {
                cached = nil
                return value
            }
            var u1 = uniform()
            if u1 < .leastNormalMagnitude { u1 = .leastNormalMagnitude }
            let u2 = uniform()
            let radius = (-2.0 * Foundation.log(u1)).squareRoot()
            cached = radius * sin(2.0 * .pi * u2)
            return radius * cos(2.0 * .pi * u2)
        }
    }

    /// Mirror of the oracle harness's `PlantedEnvelopes`: a noisy quiet
    /// world (`N(0,1)·0.02 + 1.0`) with template patterns planted at
    /// exact NCC cosines.
    private struct PlantedWorld {
        let duration: Double
        private var frames: [Float]

        init(duration: Double, seed: UInt64 = 99) {
            self.duration = duration
            var rng = SeededGaussians(seed: seed)
            frames = (0..<Int(duration) * StingerEnvelope.envelopeHz).map { _ in
                Float(rng.next() * 0.02 + 1.0)
            }
        }

        /// Mirror of the oracle harness's `make_pattern`: 2 s of
        /// `N(0,1)·0.5 + 2.0`.
        static func pattern(seed: UInt64) -> [Double] {
            var rng = SeededGaussians(seed: seed)
            return (0..<(2 * StingerEnvelope.envelopeHz)).map { _ in
                rng.next() * 0.5 + 2.0
            }
        }

        /// Write a signal whose NCC against `pattern` at the plant
        /// position is EXACTLY `cosine` (Gram-Schmidt around the
        /// centered/normalized template, matching the oracle harness).
        mutating func plant(_ pattern: [Double], at seconds: Double, cosine: Double) {
            let mean = pattern.reduce(0, +) / Double(pattern.count)
            var u = pattern.map { $0 - mean }
            let uNorm = u.reduce(0) { $0 + $1 * $1 }.squareRoot()
            u = u.map { $0 / uNorm }
            var rng = SeededGaussians(seed: UInt64((seconds * 100).rounded()))
            var n = (0..<pattern.count).map { _ in rng.next() }
            let nMean = n.reduce(0, +) / Double(n.count)
            n = n.map { $0 - nMean }
            let projection = zip(n, u).reduce(0.0) { $0 + $1.0 * $1.1 }
            n = zip(n, u).map { $0.0 - projection * $0.1 }
            let nNorm = n.reduce(0) { $0 + $1 * $1 }.squareRoot()
            n = n.map { $0 / nNorm }
            let sine = (1.0 - cosine * cosine).squareRoot()
            let base = Int((seconds * Double(StingerEnvelope.envelopeHz)).rounded())
            for i in pattern.indices {
                frames[base + i] = Float(cosine * u[i] + sine * n[i] + 2.0)
            }
        }

        /// The ±90 s search envelope the service would hand the refiner
        /// for a proposal edge at `center` (same span math as
        /// `loadStingerSearchEnvelope` and the oracle's
        /// `joint_peak_candidates`).
        func envelope(center: Double) -> StingerSearchEnvelope {
            let spanStart = max(0.0, center - StingerRefiner.searchRadiusSeconds)
            let spanEnd = min(duration, center + StingerRefiner.searchRadiusSeconds)
            let hz = Double(StingerEnvelope.envelopeHz)
            let i = Int((spanStart * hz).rounded())
            let j = min(Int((spanEnd * hz).rounded()), frames.count)
            return StingerSearchEnvelope(values: Array(frames[i..<j]), startSeconds: spanStart)
        }
    }

    private static func parityTemplate(_ pattern: [Double], confidence: Double) -> StingerTemplate {
        StingerTemplate(
            template: pattern.map(Float.init),
            edgeSampleIndex: 0,
            edgeOffsetSeconds: 0,
            confidence: confidence,
            support: 3
        )
    }

    @Test("Parity P1: the eat-class lone off-grid widening resolves to NO widening")
    func parityEatClassRejected() throws {
        // The defect this whole bead exists to kill, in planted form: a
        // gate-clearing (0.6) but grid-inconsistent end candidate that
        // would widen 66.5s into content (width 76.5 rounds to the 3×30
        // pod and sits 13.5s off it). The product penalty
        // 0.08·13.5·66.5/75 ≈ 0.958 drives it below the no-snap floor
        // (0.6 − 0.958 < 0); below-0.65 it cannot derive a rescuing
        // partner (exactly the live morbid-05-29 0.525 shape).
        // Oracle P1: [50, 60] → [50, 60]; pair_score 0.0.
        var world = PlantedWorld(duration: 600)
        let post = PlantedWorld.pattern(seed: 4)
        world.plant(post, at: 126.5, cosine: 0.6)
        let result = StingerRefiner.refine(
            proposalStart: 50.0,
            proposalEnd: 60.0,
            entry: Self.entry(post: Self.parityTemplate(post, confidence: 0.6), grid: 30.0),
            startEnvelope: nil,
            endEnvelope: world.envelope(center: 60.0),
            episodeDuration: world.duration
        )
        #expect(result.startTime == 50.0)
        #expect(result.endTime == 60.0, "the eat candidate must lose to the no-snap floor (got \(result.endTime))")
        #expect(!result.trace.endSnapped)
        #expect(!result.trace.gridApplied)
        #expect(result.trace.endCandidateCount == 1, "the candidate was enumerated — it lost on score")
        #expect(result.trace.pairScore == 0.0)
    }

    @Test("Parity P2: a near-grid widening of the same peak strength survives")
    func parityNearGridWideningSurvives() throws {
        // The counter-instance thresholds can't separate: same 0.6 peak,
        // width 64 sits only 4s off-grid → penalty 0.08·4·54/75 ≈ 0.23,
        // score 0.364 > 0 → the snap stands.
        // Oracle P2: [50, 60] → [50, 114]; pair_score 0.3642.
        var world = PlantedWorld(duration: 600)
        let post = PlantedWorld.pattern(seed: 4)
        world.plant(post, at: 114.0, cosine: 0.6)
        let result = StingerRefiner.refine(
            proposalStart: 50.0,
            proposalEnd: 60.0,
            entry: Self.entry(post: Self.parityTemplate(post, confidence: 0.6), grid: 30.0),
            startEnvelope: nil,
            endEnvelope: world.envelope(center: 60.0),
            episodeDuration: world.duration
        )
        #expect(result.startTime == 50.0)
        #expect(abs(result.endTime - 114.0) < 0.05, "got \(result.endTime)")
        #expect(result.trace.endSnapped)
        #expect(result.trace.gridTermApplied == "penalty")
        let pairScore = try #require(result.trace.pairScore)
        #expect(abs(pairScore - 0.3642) < 0.001, "oracle pair_score 0.3642 (got \(pairScore))")
    }

    @Test("Parity P3: a small sliver widening survives even far off-grid")
    func paritySliverSmallWideningSurvives() throws {
        // Width 13.1 is 16.9s off-grid but the widening is only 1.1s —
        // the penalty scales with CLAIMED CONTENT, not distance alone:
        // 0.08·16.9·1.1/75 ≈ 0.02 (the correct +1.16s-style snap lives).
        // Oracle P3: [2830, 2842] → [2830, 2843.1]; pair_score 0.5801.
        var world = PlantedWorld(duration: 4000)
        let post = PlantedWorld.pattern(seed: 5)
        world.plant(post, at: 2843.1, cosine: 0.6)
        let result = StingerRefiner.refine(
            proposalStart: 2830.0,
            proposalEnd: 2842.0,
            entry: Self.entry(post: Self.parityTemplate(post, confidence: 0.6), grid: 30.0),
            startEnvelope: nil,
            endEnvelope: world.envelope(center: 2842.0),
            episodeDuration: world.duration
        )
        #expect(result.startTime == 2830.0)
        #expect(abs(result.endTime - 2843.1) < 0.05, "got \(result.endTime)")
        #expect(result.trace.endSnapped)
        let pairScore = try #require(result.trace.pairScore)
        #expect(abs(pairScore - 0.5801) < 0.001, "oracle pair_score 0.5801 (got \(pairScore))")
    }

    @Test("Parity P4: the on-grid both-edges pair beats a STRONGER grid-inconsistent peak")
    func parityBonusPrefersGridConsistentPair() throws {
        // End candidates at 143.0 (0.95, width 48 = 12s off-grid) and
        // 155.2 (0.90, width 60.2 = on-grid). Independent argmax would
        // take 0.95; the joint bonus + penalty flip it: the on-grid pair
        // scores 0.8+0.9+0.5 ≈ 2.197 vs 0.8+0.95−0.23 ≈ 1.518.
        // Oracle P4: [100, 130] → [95, 155.2]; pair_score 2.197.
        var world = PlantedWorld(duration: 600)
        let pre = PlantedWorld.pattern(seed: 7)
        let post = PlantedWorld.pattern(seed: 8)
        world.plant(pre, at: 95.0, cosine: 0.8)
        world.plant(post, at: 143.0, cosine: 0.95)
        world.plant(post, at: 155.2, cosine: 0.9)
        let result = StingerRefiner.refine(
            proposalStart: 100.0,
            proposalEnd: 130.0,
            entry: Self.entry(
                pre: Self.parityTemplate(pre, confidence: 0.6),
                post: Self.parityTemplate(post, confidence: 0.6),
                grid: 30.0
            ),
            startEnvelope: world.envelope(center: 100.0),
            endEnvelope: world.envelope(center: 130.0),
            episodeDuration: world.duration
        )
        #expect(abs(result.startTime - 95.0) < 0.05, "got \(result.startTime)")
        #expect(abs(result.endTime - 155.2) < 0.05, "the grid-consistent pair must beat the stronger off-grid peak (got \(result.endTime))")
        #expect(result.trace.startSnapped)
        #expect(result.trace.endSnapped)
        #expect(result.trace.gridTermApplied == "bonus")
        let pairScore = try #require(result.trace.pairScore)
        #expect(abs(pairScore - 2.197) < 0.001, "oracle pair_score 2.197 (got \(pairScore))")
    }

    @Test("Parity P5: a confident (0.9) anchor derives the nearest on-grid partner")
    func parityConfidentAnchorDerives() throws {
        // Oracle P5: [105, 120] → [100, 130]; end derived; grid_applied;
        // pair_score 1.3985.
        var world = PlantedWorld(duration: 600)
        let pre = PlantedWorld.pattern(seed: 10)
        world.plant(pre, at: 100.0, cosine: 0.9)
        let result = StingerRefiner.refine(
            proposalStart: 105.0,
            proposalEnd: 120.0,
            entry: Self.entry(pre: Self.parityTemplate(pre, confidence: 0.6), grid: 30.0),
            startEnvelope: world.envelope(center: 105.0),
            endEnvelope: nil,
            episodeDuration: world.duration
        )
        #expect(abs(result.startTime - 100.0) < 0.05, "got \(result.startTime)")
        #expect(abs(result.endTime - 130.0) < 0.06, "the derived on-grid partner must set the end (got \(result.endTime))")
        #expect(result.trace.startSnapped)
        #expect(!result.trace.endSnapped)
        #expect(result.trace.gridApplied)
        let pairScore = try #require(result.trace.pairScore)
        #expect(abs(pairScore - 1.3985) < 0.001, "oracle pair_score 1.3985 (got \(pairScore))")
    }

    @Test("Parity P6: a weak (0.6 < 0.65) anchor derives NOTHING — the derived-candidate gate")
    func parityWeakAnchorDerivesNothing() throws {
        // Load-bearing sweep finding: at gate 0.50 the eat peak derives
        // its own on-grid partner and the eat returns. Same world as P5
        // at cosine 0.6: the snap stands but no partner appears.
        // Oracle P6: [105, 120] → [100, 120]; pair_score 0.5462.
        var world = PlantedWorld(duration: 600)
        let pre = PlantedWorld.pattern(seed: 10)
        world.plant(pre, at: 100.0, cosine: 0.6)
        let result = StingerRefiner.refine(
            proposalStart: 105.0,
            proposalEnd: 120.0,
            entry: Self.entry(pre: Self.parityTemplate(pre, confidence: 0.6), grid: 30.0),
            startEnvelope: world.envelope(center: 105.0),
            endEnvelope: nil,
            episodeDuration: world.duration
        )
        #expect(abs(result.startTime - 100.0) < 0.05, "got \(result.startTime)")
        #expect(result.endTime == 120.0, "no derived partner may appear below the 0.65 anchor gate (got \(result.endTime))")
        #expect(!result.trace.gridApplied)
        #expect(result.trace.endCandidateCount == nil)
        let pairScore = try #require(result.trace.pairScore)
        #expect(abs(pairScore - 0.5462) < 0.001, "oracle pair_score 0.5462 (got \(pairScore))")
    }

    @Test("Parity P7a: UNCAPPED, a neighbor break's stinger is stitched into a 4-pod super-window")
    func parityUncappedGridMultipleGobbles() throws {
        // The morbid-05-29 break-4 gobble from the sweep: without the
        // learned max-multiple cap, width 117.3 ≈ 4×30 is "on-grid" and
        // the pair takes the bonus.
        // Oracle P7a: [4076, 4096.4] → [4036, 4153.3]; pair_score 1.9903.
        var world = PlantedWorld(duration: 6000)
        let pre = PlantedWorld.pattern(seed: 11)
        let post = PlantedWorld.pattern(seed: 12)
        world.plant(pre, at: 4036.0, cosine: 0.9)
        world.plant(post, at: 4153.3, cosine: 0.6)
        let result = StingerRefiner.refine(
            proposalStart: 4076.0,
            proposalEnd: 4096.4,
            entry: Self.entry(
                pre: Self.parityTemplate(pre, confidence: 0.6),
                post: Self.parityTemplate(post, confidence: 0.6),
                grid: 30.0
            ),
            startEnvelope: world.envelope(center: 4076.0),
            endEnvelope: world.envelope(center: 4096.4),
            episodeDuration: world.duration
        )
        #expect(abs(result.startTime - 4036.0) < 0.05)
        #expect(abs(result.endTime - 4153.3) < 0.05, "uncapped, width 117.3 ≈ 4×30 earns the bonus (got \(result.endTime))")
        let pairScore = try #require(result.trace.pairScore)
        #expect(abs(pairScore - 1.9903) < 0.001, "oracle pair_score 1.9903 (got \(pairScore))")
    }

    @Test("Parity P7b: the show's learned max multiple (3) rejects the gobble; the derived pod wins")
    func parityCappedGridMultipleRejectsGobble() throws {
        // Capped at 3, the 117.3s pair is off-grid by construction
        // (distance 27.3 from 3×30) and dies under the widening penalty;
        // the confident 4036 anchor's derived 60s pod takes the end
        // instead.
        // Oracle P7b: [4076, 4096.4] → [4036, 4096.0]; end derived;
        // pair_score 1.396.
        var world = PlantedWorld(duration: 6000)
        let pre = PlantedWorld.pattern(seed: 11)
        let post = PlantedWorld.pattern(seed: 12)
        world.plant(pre, at: 4036.0, cosine: 0.9)
        world.plant(post, at: 4153.3, cosine: 0.6)
        let result = StingerRefiner.refine(
            proposalStart: 4076.0,
            proposalEnd: 4096.4,
            entry: Self.entry(
                pre: Self.parityTemplate(pre, confidence: 0.6),
                post: Self.parityTemplate(post, confidence: 0.6),
                grid: 30.0,
                gridMaxMultiple: 3
            ),
            startEnvelope: world.envelope(center: 4076.0),
            endEnvelope: world.envelope(center: 4096.4),
            episodeDuration: world.duration
        )
        #expect(abs(result.startTime - 4036.0) < 0.05)
        #expect(abs(result.endTime - 4096.0) < 0.06, "the capped recipe must land the derived 60s pod, not the neighbor stinger (got \(result.endTime))")
        #expect(!result.trace.endSnapped, "the neighbor peak must NOT win the end")
        #expect(result.trace.gridApplied)
        let pairScore = try #require(result.trace.pairScore)
        #expect(abs(pairScore - 1.396) < 0.001, "oracle pair_score 1.396 (got \(pairScore))")
    }

    @Test("Parity P8: equal peaks resolve by the 1e-4/s movement tie-break — nearer wins")
    func parityMovementTiebreak() throws {
        // Two EXACTLY equal 0.9 plants at 138 (move 12) and 158 (move 8):
        // the only separating term is 1e-4·move.
        // Oracle P8: [100, 150] → [100, 158]; pair_score 0.8992.
        var world = PlantedWorld(duration: 600)
        let post = PlantedWorld.pattern(seed: 6)
        world.plant(post, at: 138.0, cosine: 0.9)
        world.plant(post, at: 158.0, cosine: 0.9)
        let result = StingerRefiner.refine(
            proposalStart: 100.0,
            proposalEnd: 150.0,
            entry: Self.entry(post: Self.parityTemplate(post, confidence: 0.9)),
            startEnvelope: nil,
            endEnvelope: world.envelope(center: 150.0),
            episodeDuration: world.duration
        )
        #expect(result.startTime == 100.0)
        #expect(abs(result.endTime - 158.0) < 0.05, "the nearer of two equal peaks must win (got \(result.endTime))")
        #expect(result.trace.endCandidateCount == 2)
        let pairScore = try #require(result.trace.pairScore)
        #expect(abs(pairScore - 0.8992) < 0.001, "oracle pair_score 0.8992 (got \(pairScore))")
    }

    @Test("Parity P9: candidate enumeration honors gate and move cap; the strongest survivor wins")
    func parityMoveCapAndStrongestPeak() throws {
        // Plants at 100 (1.0), 130 (0.9), 190 (0.95, move 70 — within the
        // cap) and 199 (0.95, move 79 — EXCLUDED). Three candidates
        // enumerate; the strongest (1.0) wins.
        // Oracle P9: [120, 300] → [100, 300]; pair_score 0.998.
        var world = PlantedWorld(duration: 600)
        let pre = PlantedWorld.pattern(seed: 1)
        world.plant(pre, at: 100.0, cosine: 1.0)
        world.plant(pre, at: 130.0, cosine: 0.9)
        world.plant(pre, at: 190.0, cosine: 0.95)
        world.plant(pre, at: 199.0, cosine: 0.95)
        let result = StingerRefiner.refine(
            proposalStart: 120.0,
            proposalEnd: 300.0,
            entry: Self.entry(pre: Self.parityTemplate(pre, confidence: 0.9)),
            startEnvelope: world.envelope(center: 120.0),
            endEnvelope: nil,
            episodeDuration: world.duration
        )
        #expect(abs(result.startTime - 100.0) < 0.05, "got \(result.startTime)")
        #expect(result.endTime == 300.0)
        #expect(result.trace.startCandidateCount == 3, "the 199s plant moves 79s and must be excluded by the cap")
        let pairScore = try #require(result.trace.pairScore)
        #expect(abs(pairScore - 0.998) < 0.001, "oracle pair_score 0.998 (got \(pairScore))")
    }

    @Test("Parity P10: an off-grid NARROWING snap pays no inconsistency penalty (inward exemption)")
    func parityInwardNarrowingPaysNoPenalty() throws {
        // The penalty scales with WIDENING (content claimed beyond the
        // proposal), never with movement per se: an inward 24 s end snap
        // to an off-grid width (56 → 4 s from the 2×30 pod) pays exactly
        // zero — "Inward (narrowing) moves pay nothing" (JointConfig
        // docstring; narrowing is already governed by the peak terms).
        // Every other penalty fixture moves its edge OUTWARD only, where
        // widening == total movement — this is the scenario that
        // separates the two: a moved-based mis-port would score
        // 0.6 − 0.08·4·24/75 − 0.0024 = 0.4952, not 0.5976.
        // Oracle P10: [50, 130] → [50, 106.0]; end_snapped;
        // grid_applied false; pair_score 0.5976.
        var world = PlantedWorld(duration: 600)
        let post = PlantedWorld.pattern(seed: 4)
        world.plant(post, at: 106.0, cosine: 0.6)
        let result = StingerRefiner.refine(
            proposalStart: 50.0,
            proposalEnd: 130.0,
            entry: Self.entry(post: Self.parityTemplate(post, confidence: 0.6), grid: 30.0),
            startEnvelope: nil,
            endEnvelope: world.envelope(center: 130.0),
            episodeDuration: world.duration
        )
        #expect(result.startTime == 50.0)
        #expect(abs(result.endTime - 106.0) < 0.05, "the narrowing snap must stand (got \(result.endTime))")
        #expect(result.trace.endSnapped)
        #expect(!result.trace.gridApplied)
        #expect(result.trace.gridTermApplied == nil, "zero widening ⇒ zero penalty ⇒ no grid term recorded")
        #expect(result.trace.endCandidateCount == 1)
        let pairScore = try #require(result.trace.pairScore)
        #expect(abs(pairScore - 0.5976) < 0.001, "oracle pair_score 0.5976 (got \(pairScore))")
    }

    @Test("Parity P11: widening sums OUTWARD movement across both edges — the narrowing edge contributes zero")
    func parityWideningSumsOutwardMovementOnly() throws {
        // Mixed pair: the start widens 9 s (50 → 41) while the end
        // narrows 24 s (130 → 106); width 65 sits 5 s off the 2×30 pod.
        // The penalty charges ONLY the 9 s of claimed content:
        // 0.08·5·9/75 = 0.048. A total-movement mis-port would charge
        // 33 s (score 1.0207); an end-edge-only-widening mis-port would
        // charge nothing (score 1.1967) — both outside the ±0.001 pin.
        // Oracle P11: [50, 130] → [41.0, 106.0]; both snapped;
        // grid_applied false; pair_score 1.1487.
        var world = PlantedWorld(duration: 600)
        let pre = PlantedWorld.pattern(seed: 7)
        let post = PlantedWorld.pattern(seed: 4)
        world.plant(pre, at: 41.0, cosine: 0.6)
        world.plant(post, at: 106.0, cosine: 0.6)
        let result = StingerRefiner.refine(
            proposalStart: 50.0,
            proposalEnd: 130.0,
            entry: Self.entry(
                pre: Self.parityTemplate(pre, confidence: 0.6),
                post: Self.parityTemplate(post, confidence: 0.6),
                grid: 30.0
            ),
            startEnvelope: world.envelope(center: 50.0),
            endEnvelope: world.envelope(center: 130.0),
            episodeDuration: world.duration
        )
        #expect(abs(result.startTime - 41.0) < 0.05, "got \(result.startTime)")
        #expect(abs(result.endTime - 106.0) < 0.05, "got \(result.endTime)")
        #expect(result.trace.startSnapped)
        #expect(result.trace.endSnapped)
        #expect(!result.trace.gridApplied)
        #expect(result.trace.gridTermApplied == "penalty", "the off-grid pair pays a nonzero (start-widening-only) penalty")
        #expect(result.trace.startCandidateCount == 1)
        #expect(result.trace.endCandidateCount == 1)
        let pairScore = try #require(result.trace.pairScore)
        #expect(abs(pairScore - 1.1487) < 0.001, "oracle pair_score 1.1487 (got \(pairScore))")
    }

    // MARK: - Envelope computation

    @Test("StingerEnvelope computes 50 Hz log1p(rms*100) frames and drops the partial tail")
    func envelopeComputation() {
        // One second of constant 0.5 at 16 kHz → 50 frames of
        // log1p(0.5 * 100) = ln(51).
        let oneSecond = [Float](repeating: 0.5, count: 16_000)
        let envelope = StingerEnvelope.compute(samples: oneSecond)
        #expect(envelope.count == 50)
        let expected = Float(log1p(50.0))
        for value in envelope {
            #expect(abs(value - expected) < 0.0001)
        }

        // 703 samples = 2 full 320-sample hops + 63 dropped.
        let short = [Float](repeating: 0.25, count: 703)
        #expect(StingerEnvelope.compute(samples: short).count == 2)

        // Below one hop → empty.
        #expect(StingerEnvelope.compute(samples: [Float](repeating: 1, count: 319)).isEmpty)
    }
}
