// StingerCandidateMinerTests.swift
// playhead-xsdz.42d: unit + port-parity tests for the gold-free per-show
// stinger candidate miner. No audio, no actor, no bundle, no gold.
//
// Three groups, all in ONE suite struct so a single
// `-only-testing:'PlayheadTests/StingerCandidateMinerTests'` runs them:
//   1. DEMOTION LOGIC (pure): `passesMultiplicity` / `stableMultiplicityRank`
//      on hand-built candidates — the stage-3 re-rank contract, no NCC.
//   2. SEMANTICS (integrated): run `mine` on planted synthetic corpora and
//      assert the headline behaviors — mid-roll stinger promoted over a
//      once-firing outro, single-break fallback vs hard-gate empties, the
//      silence gate, determinism, and output-shape invariants.
//   3. PORT PARITY: reproduce the xsdz.42d prototype's ranking on a fixture
//      generated by the REAL prototype functions
//      (`scripts/l2f-xsdz42d-miner-parity-fixture.py`, direct == FFT verified).
//      Discrete fields (side, vote, multiplicity, pass, order) match exactly;
//      NCC floats match within a documented tolerance.

import Foundation
import Testing
@testable import Playhead

// `.serialized`: the envelope-NCC integrated tests each allocate and scan
// multi-thousand-frame envelopes. Running them in parallel WITHIN this suite
// stacks that memory/CPU on top of the rest of the FastTests fan-out (and any
// concurrent build), which can starve the test host. Serializing this suite
// caps its footprint to one test at a time; other suites still parallelize
// around it, so the whole-plan wall time is unaffected.
@Suite("StingerCandidateMiner (playhead-xsdz.42d)", .serialized)
struct StingerCandidateMinerTests {

    // MARK: - 1. Demotion logic (pure)

    private static func candidate(
        center: Double,
        side: MinedStingerSide = .pre,
        within: [String: Int],
        votingCount: Int,
        passes: Bool
    ) -> MinedStingerCandidate {
        MinedStingerCandidate(
            side: side,
            template: [Float](repeating: 1.0, count: 350),
            sourceEpisodeId: "ep",
            anchorSeconds: center,
            centerSeconds: center,
            edgeOffsetSeconds: 0,
            vote: max(1, votingCount),
            medianPartnerNCC: 1.0,
            partners: [],
            withinMultiplicity: within,
            votingEpisodeCount: votingCount,
            multiplicityPasses: passes,
            silentFraction: 0
        )
    }

    @Test("passesMultiplicity: any-quorum needs one multiplying episode")
    func passesMultiplicityAnyQuorum() {
        // {2,1,3}: two episodes multiply at min=2 -> passes for `any`.
        #expect(StingerCandidateMiner.passesMultiplicity(
            withinMultiplicity: ["a": 2, "b": 1, "c": 3], votingEpisodeCount: 3,
            multiplicityMin: 2, quorum: .any))
        // {1,1}: none multiplies -> fails.
        #expect(!StingerCandidateMiner.passesMultiplicity(
            withinMultiplicity: ["a": 1, "b": 1], votingEpisodeCount: 2,
            multiplicityMin: 2, quorum: .any))
    }

    @Test("passesMultiplicity: majority-quorum needs ceil(V/2) multiplying")
    func passesMultiplicityMajorityQuorum() {
        // {2,1,1}: one multiplies, need ceil(3/2)=2 -> fails.
        #expect(!StingerCandidateMiner.passesMultiplicity(
            withinMultiplicity: ["a": 2, "b": 1, "c": 1], votingEpisodeCount: 3,
            multiplicityMin: 2, quorum: .majority))
        // {2,3,1}: two multiply, need 2 -> passes.
        #expect(StingerCandidateMiner.passesMultiplicity(
            withinMultiplicity: ["a": 2, "b": 3, "c": 1], votingEpisodeCount: 3,
            multiplicityMin: 2, quorum: .majority))
    }

    @Test("passesMultiplicity: multiplicityMin=3 requires >=3 firings")
    func passesMultiplicityMultMinThree() {
        #expect(!StingerCandidateMiner.passesMultiplicity(
            withinMultiplicity: ["a": 2, "b": 2], votingEpisodeCount: 2,
            multiplicityMin: 3, quorum: .any))
        #expect(StingerCandidateMiner.passesMultiplicity(
            withinMultiplicity: ["a": 3, "b": 2], votingEpisodeCount: 2,
            multiplicityMin: 3, quorum: .any))
    }

    @Test("stableMultiplicityRank: passing precede failing, order preserved")
    func stableRankPartitionsPassingBeforeFailing() {
        let a = Self.candidate(center: 10, within: ["a": 2], votingCount: 1, passes: true)
        let b = Self.candidate(center: 20, within: ["a": 1], votingCount: 1, passes: false)
        let c = Self.candidate(center: 30, within: ["a": 2], votingCount: 1, passes: true)
        let d = Self.candidate(center: 40, within: ["a": 1], votingCount: 1, passes: false)
        let ranked = StingerCandidateMiner.stableMultiplicityRank([a, b, c, d], hardGate: false)
        #expect(ranked.map(\.centerSeconds) == [10, 30, 20, 40],
                "stable partition: [passing in order] ++ [failing in order]")
    }

    @Test("stableMultiplicityRank: hard gate drops the failing group")
    func stableRankHardGateDropsFailing() {
        let a = Self.candidate(center: 10, within: ["a": 2], votingCount: 1, passes: true)
        let b = Self.candidate(center: 20, within: ["a": 1], votingCount: 1, passes: false)
        #expect(StingerCandidateMiner.stableMultiplicityRank([a, b], hardGate: true)
            .map(\.centerSeconds) == [10])
        // A single-break show where nothing multiplies empties under hard gate.
        #expect(StingerCandidateMiner.stableMultiplicityRank([b], hardGate: true).isEmpty)
    }

    @Test("stableMultiplicityRank: a single group is a no-op (order unchanged)")
    func stableRankSingleGroupIsNoOp() {
        let a = Self.candidate(center: 10, within: ["a": 1], votingCount: 1, passes: false)
        let b = Self.candidate(center: 20, within: ["a": 1], votingCount: 1, passes: false)
        #expect(StingerCandidateMiner.stableMultiplicityRank([a, b], hardGate: false)
            .map(\.centerSeconds) == [10, 20])
    }

    // MARK: - Synthetic corpus builders (integrated tests)

    /// Deterministic pseudo-random values in `[lo, hi)` (seeded LCG — stable
    /// across runs/platforms). Non-constant so every window has real variance.
    private static func pattern(count: Int, seed: UInt64, lo: Float, hi: Float) -> [Float] {
        var state = seed &+ 0x9E37_79B9_7F4A_7C15
        return (0..<count).map { _ in
            state = state &* 6_364_136_223_846_793_005 &+ 1_442_695_040_888_963_407
            let unit = Float(state >> 40) / Float(1 << 24)
            return lo + unit * (hi - lo)
        }
    }

    /// A distinctive, non-silent 7 s motif (all values >= the 0.5 silence
    /// threshold so its aligned window survives the silence gate).
    private static func motif(seed: UInt64) -> [Float] {
        pattern(count: 350, seed: seed, lo: 0.6, hi: 3.0)
    }

    /// Overlay motifs on a per-episode low-amplitude noise floor (sub-threshold
    /// "silent" but non-constant, avoiding zero-variance NCC instability).
    private static func envelope(
        frames: Int,
        backgroundSeed: UInt64,
        plantings: [(frame: Int, pattern: [Float])],
        bgLo: Float = 0.02,
        bgHi: Float = 0.30
    ) -> [Float] {
        var env = pattern(count: frames, seed: backgroundSeed, lo: bgLo, hi: bgHi)
        for planting in plantings {
            for (i, v) in planting.pattern.enumerated() where planting.frame + i < frames {
                env[planting.frame + i] = v
            }
        }
        return env
    }

    private static func span(_ start: Double, _ end: Double) -> StingerMinerAdCandidate {
        StingerMinerAdCandidate(startSeconds: start, endSeconds: end)
    }

    /// Compact config for the integrated semantic tests: a 12 s search radius —
    /// below the corpus's 16 s break separation (so each anchor's window sees a
    /// single break) and small enough that every test stays light and
    /// parallel-safe. The algorithm is radius-parametric; the same value drives
    /// the parity fixture generator.
    private static let fastConfig: StingerMinerConfig = {
        var c = StingerMinerConfig.default
        c.searchRadiusSeconds = 12.0
        return c
    }()

    // MARK: - 2. Semantics (integrated)

    @Test("Fewer than two candidate-bearing episodes yields no candidates")
    func insufficientEpisodesReturnsEmpty() {
        let stinger = Self.motif(seed: 1)
        let withCandidate = StingerMinerEpisode(
            id: "show-01", envelope: Self.envelope(
                frames: 2000, backgroundSeed: 11, plantings: [(500, stinger)]),
            adCandidates: [Self.span(10, 17)])
        let noCandidate = StingerMinerEpisode(
            id: "show-02", envelope: Self.envelope(
                frames: 2000, backgroundSeed: 12, plantings: [(500, stinger)]),
            adCandidates: [])
        #expect(StingerCandidateMiner.mine(episodes: [withCandidate, noCandidate],
                                           config: Self.fastConfig).isEmpty)
        #expect(StingerCandidateMiner.mine(episodes: [withCandidate],
                                           config: Self.fastConfig).isEmpty)
    }

    /// A 3-episode show: mid-roll stinger S at two breaks in ep1/ep2, outro cue
    /// O once per episode in all three (mirrors the parity corpus). Reused by
    /// several tests.
    private static func stingerVsOutroShow() -> [StingerMinerEpisode] {
        let stinger = Self.motif(seed: 101)
        let outro = Self.motif(seed: 202)
        return (0..<3).map { k in
            var plantings: [(frame: Int, pattern: [Float])] = [(2000, outro)]   // @40s
            if k < 2 { plantings = [(400, stinger), (1200, stinger)] + plantings } // @8s, @24s
            return StingerMinerEpisode(
                id: "show-2026-01-0\(k + 1)",
                envelope: Self.envelope(frames: 2400, backgroundSeed: UInt64(700 + k),
                                        plantings: plantings),
                adCandidates: [Self.span(8, 15), Self.span(24, 31), Self.span(40, 47)])
        }
    }

    @Test("Multiplicity promotes the mid-roll stinger above the once-firing outro")
    func midrollStingerPromotedOverOutro() throws {
        let result = StingerCandidateMiner.mine(episodes: Self.stingerVsOutroShow(),
                                                config: Self.fastConfig)
        #expect(!result.isEmpty)
        // Demotion partition: every passing candidate precedes every failing one.
        let firstFailing = result.firstIndex { !$0.multiplicityPasses } ?? result.count
        let prefixAllPass = result[..<firstFailing].allSatisfy(\.multiplicityPasses)
        let suffixAllFail = result[firstFailing...].allSatisfy { !$0.multiplicityPasses }
        #expect(prefixAllPass)
        #expect(suffixAllFail)
        // The top candidate is a passing (mid-roll) stinger, not the outro —
        // even though the outro carries the higher consensus vote (3 vs 2).
        let top = try #require(result.first)
        #expect(top.multiplicityPasses)
        let topFiresTwice = top.withinMultiplicity.values.contains { $0 >= 2 }
        #expect(topFiresTwice, "the promoted stinger fires >= 2x within a voting episode")
        // The outro appears and fails: vote 3, fires exactly once per episode.
        let outro = try #require(result.first { $0.vote == 3 })
        #expect(!outro.multiplicityPasses)
        let outroFiresOnce = outro.withinMultiplicity.values.allSatisfy { $0 == 1 }
        #expect(outroFiresOnce)
    }

    @Test("Deterministic: identical inputs yield an identical ranking")
    func deterministicAcrossRuns() {
        // A compact two-episode show (one mid-roll break each, shared stinger)
        // is enough to exercise consensus + NMS + multiplicity deterministically.
        let stinger = Self.motif(seed: 555)
        let show = (0..<2).map { k in
            StingerMinerEpisode(
                id: "det-0\(k + 1)",
                envelope: Self.envelope(frames: 1600, backgroundSeed: UInt64(60 + k),
                                        plantings: [(500, stinger)]),
                adCandidates: [Self.span(10, 17)])
        }
        let a = StingerCandidateMiner.mine(episodes: show, config: Self.fastConfig)
        let b = StingerCandidateMiner.mine(episodes: show, config: Self.fastConfig)
        #expect(a == b)
        #expect(!a.isEmpty)
    }

    @Test("Single-break show: demotion keeps the pre-roll, hard gate empties it")
    func singleBreakFallbackVsHardGate() {
        // Two episodes, one pre-roll break each, sharing a stinger. Nothing can
        // fire >= 2x within an episode (one break), so nothing multiplies.
        let stinger = Self.motif(seed: 303)
        let episodes = (0..<2).map { k in
            StingerMinerEpisode(
                id: "preroll-0\(k + 1)",
                envelope: Self.envelope(frames: 1600, backgroundSeed: UInt64(50 + k),
                                        plantings: [(25, stinger)]),
                adCandidates: [Self.span(0.5, 7.5)])
        }
        let demoted = StingerCandidateMiner.mine(episodes: episodes, config: Self.fastConfig)
        #expect(!demoted.isEmpty, "demotion preserves the pre-roll win")
        let noneMultiply = demoted.allSatisfy { !$0.multiplicityPasses }
        #expect(noneMultiply, "single-break show: no motif multiplies")

        var hardGate = Self.fastConfig
        hardGate.hardGate = true
        #expect(StingerCandidateMiner.mine(episodes: episodes, config: hardGate).isEmpty,
                "hard gate empties a single-break show (spike Result 5)")
    }

    @Test("Silence gate drops a sub-threshold recurring motif")
    func silenceGateDropsSubThresholdMotif() {
        // A quiet, distinctive, RECURRING motif whose every value sits below the
        // 0.5 silence threshold — a splice-silence bumper, not a musical cue.
        let quiet = Self.pattern(count: 350, seed: 404, lo: 0.10, hi: 0.45)
        let episodes = (0..<2).map { k in
            StingerMinerEpisode(
                id: "quiet-0\(k + 1)",
                envelope: Self.envelope(frames: 1600, backgroundSeed: UInt64(90 + k),
                                        plantings: [(500, quiet)], bgLo: 0.02, bgHi: 0.06),
                adCandidates: [Self.span(10, 17)])
        }
        #expect(StingerCandidateMiner.mine(episodes: episodes, config: Self.fastConfig).isEmpty,
                "silence gate ON drops the sub-threshold motif")

        var gateOff = Self.fastConfig
        gateOff.silenceGateEnabled = false
        #expect(!StingerCandidateMiner.mine(episodes: episodes, config: gateOff).isEmpty,
                "with the gate OFF the recurring sub-threshold motif surfaces")
    }

    @Test("Every candidate has bank-shaped template and consistent fields")
    func candidateShapeAndFieldConsistency() {
        let result = StingerCandidateMiner.mine(episodes: Self.stingerVsOutroShow(),
                                                config: Self.fastConfig)
        #expect(!result.isEmpty)
        for candidate in result {
            #expect(candidate.template.count == Self.fastConfig.templateFrames,
                    "template is the shipped bank shape (\(Self.fastConfig.templateFrames) frames)")
            let templateFinite = candidate.template.allSatisfy(\.isFinite)
            #expect(templateFinite)
            #expect(candidate.vote == 1 + candidate.partners.count)
            #expect(candidate.votingEpisodeCount >= 1)
            #expect(candidate.votingEpisodeCount == candidate.withinMultiplicity.count)
            // edgeOffset == center - anchor, up to 0.1 rounding.
            #expect(abs(candidate.edgeOffsetSeconds
                        - (candidate.centerSeconds - candidate.anchorSeconds)) < 0.06)
        }
    }

    // MARK: - 3. Port parity

    private static let parityFilePath = #filePath

    private struct Fixture: Decodable {
        struct Config: Decodable {
            let envelopeHz: Int
            let templateFrames: Int
            let searchRadiusSeconds: Double
            let deltaHopFrames: Int
            let consensusTau: Double
            let offsetToleranceSeconds: Double
            let minEpisodeVote: Int
            let topK: Int
            let silenceGateEnabled: Bool
            let silentEnvelopeThreshold: Float
            let silentFractionGate: Double
            let acousticDedupeNCC: Double
            let nmsRadiusFrames: Int
            let withinTau: Double
            let multiplicityMin: Int
            let quorum: String
            let hardGate: Bool
        }
        struct Episode: Decodable {
            let id: String
            let envelope: [Float]
            let adCandidates: [Candidate]
            struct Candidate: Decodable { let startSeconds: Double; let endSeconds: Double }
        }
        struct Expected: Decodable {
            let side: String
            let sourceEpisodeId: String
            let anchorSeconds: Double
            let centerSeconds: Double
            let edgeOffsetSeconds: Double
            let vote: Int
            let medianPartnerNCC: Double
            let partners: [Partner]
            let withinMultiplicity: [String: Int]
            let votingEpisodeCount: Int
            let multiplicityPasses: Bool
            let silentFraction: Double
            let template: [Float]
            struct Partner: Decodable { let episodeId: String; let peakNCC: Double }
        }
        let config: Config
        let episodes: [Episode]
        let expected: [Expected]
    }

    private static func loadFixture() throws -> Fixture {
        let url = URL(fileURLWithPath: parityFilePath)
            .deletingLastPathComponent()
            .appendingPathComponent("StingerCandidateMinerParityFixture.json")
        return try JSONDecoder().decode(Fixture.self, from: Data(contentsOf: url))
    }

    private static func config(from f: Fixture.Config) -> StingerMinerConfig {
        var c = StingerMinerConfig.default
        c.envelopeHz = f.envelopeHz
        c.templateFrames = f.templateFrames
        c.searchRadiusSeconds = f.searchRadiusSeconds
        c.deltaHopFrames = f.deltaHopFrames
        c.consensusTau = f.consensusTau
        c.offsetToleranceSeconds = f.offsetToleranceSeconds
        c.minEpisodeVote = f.minEpisodeVote
        c.topK = f.topK
        c.silenceGateEnabled = f.silenceGateEnabled
        c.silentEnvelopeThreshold = f.silentEnvelopeThreshold
        c.silentFractionGate = f.silentFractionGate
        c.acousticDedupeNCC = f.acousticDedupeNCC
        c.nmsRadiusFrames = f.nmsRadiusFrames
        c.withinTau = f.withinTau
        c.multiplicityMin = f.multiplicityMin
        c.quorum = f.quorum == "majority" ? .majority : .any
        c.hardGate = f.hardGate
        return c
    }

    @Test("Port parity: Swift reproduces the xsdz.42d prototype ranking")
    func reproducesPrototypeRanking() throws {
        let fixture = try Self.loadFixture()
        let episodes = fixture.episodes.map {
            StingerMinerEpisode(
                id: $0.id, envelope: $0.envelope,
                adCandidates: $0.adCandidates.map {
                    StingerMinerAdCandidate(startSeconds: $0.startSeconds, endSeconds: $0.endSeconds)
                })
        }
        let result = StingerCandidateMiner.mine(episodes: episodes,
                                                config: Self.config(from: fixture.config))

        #expect(result.count == fixture.expected.count,
                "candidate count: got \(result.count), expected \(fixture.expected.count)")
        for (index, (got, want)) in zip(result, fixture.expected).enumerated() {
            // Discrete fields — EXACT (the ranking's structure).
            #expect(got.side.rawValue == want.side, "rank \(index) side")
            #expect(got.sourceEpisodeId == want.sourceEpisodeId, "rank \(index) source")
            #expect(got.vote == want.vote, "rank \(index) vote")
            #expect(got.votingEpisodeCount == want.votingEpisodeCount, "rank \(index) votingCount")
            #expect(got.multiplicityPasses == want.multiplicityPasses, "rank \(index) passes")
            #expect(got.withinMultiplicity == want.withinMultiplicity, "rank \(index) within-mult")
            #expect(abs(got.anchorSeconds - want.anchorSeconds) < 0.06, "rank \(index) anchorS")
            #expect(abs(got.centerSeconds - want.centerSeconds) < 0.06, "rank \(index) centerS")
            #expect(abs(got.edgeOffsetSeconds - want.edgeOffsetSeconds) < 0.06, "rank \(index) edgeOffset")
            // NCC / envelope floats — within a documented tolerance.
            #expect(abs(got.medianPartnerNCC - want.medianPartnerNCC) < 0.005, "rank \(index) medianNCC")
            #expect(abs(got.silentFraction - want.silentFraction) < 0.02, "rank \(index) silentFrac")
            #expect(got.partners.count == want.partners.count, "rank \(index) partner count")
            for (gp, wp) in zip(got.partners, want.partners) {
                #expect(gp.episodeId == wp.episodeId, "rank \(index) partner id")
                #expect(abs(gp.peakNCC - wp.peakNCC) < 0.005, "rank \(index) partner ncc")
            }
            #expect(got.template.count == want.template.count, "rank \(index) template length")
            let maxTemplateDelta = zip(got.template, want.template)
                .map { abs($0 - $1) }.max() ?? 0
            #expect(maxTemplateDelta < 1e-3, "rank \(index) template within tolerance (max Δ \(maxTemplateDelta))")
        }

        // The headline demotion holds on the real prototype fixture too: the
        // top candidate passes multiplicity, and every passing candidate
        // precedes every failing one.
        let firstFailing = result.firstIndex { !$0.multiplicityPasses } ?? result.count
        let prefixAllPass = result[..<firstFailing].allSatisfy(\.multiplicityPasses)
        let suffixAllFail = result[firstFailing...].allSatisfy { !$0.multiplicityPasses }
        #expect(prefixAllPass)
        #expect(suffixAllFail)
        #expect(result.first?.multiplicityPasses == true)
    }
}
